// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type FansListRequest struct {
	UserId int64 `form:"user_id,optional"` // 不传默认当前用户
	Page   int64 `form:"page,optional,default=1"`
	Size   int64 `form:"size,optional,default=20"`
}

type FansListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	List    []UserBrief `json:"list,optional"`
	Total   int64       `json:"total"`
	Page    int64       `json:"page"`
	Size    int64       `json:"size"`
}

type FollowListRequest struct {
	Page int64 `form:"page,optional,default=1"`
	Size int64 `form:"size,optional,default=20"`
}

type FollowListResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	List    []UserBrief `json:"list,optional"`
	Total   int64       `json:"total"`
	Page    int64       `json:"page"`
	Size    int64       `json:"size"`
}

type FollowRequest struct {
	UserId int64 `json:"user_id" validate:"required,gt=0"` // 目标用户ID
}

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type UserBrief struct {
	UserId   int64  `json:"user_id"`
	Name     string `json:"name"`
	Avatar   string `json:"avatar"`
	IsFollow bool   `json:"is_follow"` // 当前登录用户是否已关注
	IsMutual bool   `json:"is_mutual"` // 是否互相关注
}
