// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: food.proto

package server

import (
	"context"

	"github.com/hd2yao/ecshop/food/rpc/internal/logic"
	"github.com/hd2yao/ecshop/food/rpc/internal/svc"
	"github.com/hd2yao/ecshop/food/rpc/types/food"
)

type FoodServer struct {
	svcCtx *svc.ServiceContext
	food.UnimplementedFoodServer
}

func NewFoodServer(svcCtx *svc.ServiceContext) *FoodServer {
	return &FoodServer{
		svcCtx: svcCtx,
	}
}

// 查询单个美食基础信息
func (s *FoodServer) GetFood(ctx context.Context, in *food.GetFoodReq) (*food.GetFoodResp, error) {
	l := logic.NewGetFoodLogic(ctx, s.svcCtx)
	return l.GetFood(in)
}

// 查询我的美食列表
func (s *FoodServer) GetMyFoodList(ctx context.Context, in *food.GetMyFoodListReq) (*food.GetMyFoodListResp, error) {
	l := logic.NewGetMyFoodListLogic(ctx, s.svcCtx)
	return l.GetMyFoodList(in)
}

// 新增/修改美食信息
func (s *FoodServer) CreateOrUpdateFood(ctx context.Context, in *food.CreateOrUpdateFoodReq) (*food.CreateOrUpdateFoodResp, error) {
	l := logic.NewCreateOrUpdateFoodLogic(ctx, s.svcCtx)
	return l.CreateOrUpdateFood(in)
}
