// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: user.proto

package userclient

import (
	"context"

	"github.com/hd2yao/ecshop/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAddressReq           = user.AddAddressReq
	AddAddressResp          = user.AddAddressResp
	AddressInfo             = user.AddressInfo
	CaptchaConfig           = user.CaptchaConfig
	DeleteAddressReq        = user.DeleteAddressReq
	DeleteAddressResp       = user.DeleteAddressResp
	DrawOptions             = user.DrawOptions
	GenerateCaptchaReq      = user.GenerateCaptchaReq
	GenerateCaptchaResp     = user.GenerateCaptchaResp
	GetAddressDetailReq     = user.GetAddressDetailReq
	GetAddressDetailResp    = user.GetAddressDetailResp
	GetAddressListReq       = user.GetAddressListReq
	GetAddressListResp      = user.GetAddressListResp
	GetUserInfoReq          = user.GetUserInfoReq
	GetUserInfoResp         = user.GetUserInfoResp
	LoginReq                = user.LoginReq
	LoginResp               = user.LoginResp
	RefreshTokenReq         = user.RefreshTokenReq
	RefreshTokenResp        = user.RefreshTokenResp
	RegisterReq             = user.RegisterReq
	RegisterResp            = user.RegisterResp
	SendMailCodeResp        = user.SendMailCodeResp
	SendRegisterMailCodeReq = user.SendRegisterMailCodeReq
	UpdateAddressReq        = user.UpdateAddressReq
	UpdateAddressResp       = user.UpdateAddressResp
	UpdateUserInfoReq       = user.UpdateUserInfoReq
	UpdateUserInfoResp      = user.UpdateUserInfoResp
	UploadPreviewAvatarReq  = user.UploadPreviewAvatarReq
	UploadPreviewAvatarResp = user.UploadPreviewAvatarResp
	UserInfo                = user.UserInfo
	VerifyCaptchaReq        = user.VerifyCaptchaReq
	VerifyCaptchaResp       = user.VerifyCaptchaResp

	User interface {
		// 图形验证码
		GenerateCaptcha(ctx context.Context, in *GenerateCaptchaReq, opts ...grpc.CallOption) (*GenerateCaptchaResp, error)
		VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...grpc.CallOption) (*VerifyCaptchaResp, error)
		// 邮件验证码
		SendRegisterMailCode(ctx context.Context, in *SendRegisterMailCodeReq, opts ...grpc.CallOption) (*SendMailCodeResp, error)
		// 用户注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		// 头像上传
		UploadPreviewAvatar(ctx context.Context, in *UploadPreviewAvatarReq, opts ...grpc.CallOption) (*UploadPreviewAvatarResp, error)
		// 用户登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		// 刷新Token
		RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
		// 获取用户信息
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error)
		// 修改用户信息
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error)
		// 用户地址管理
		GetAddressList(ctx context.Context, in *GetAddressListReq, opts ...grpc.CallOption) (*GetAddressListResp, error)
		GetAddressDetail(ctx context.Context, in *GetAddressDetailReq, opts ...grpc.CallOption) (*GetAddressDetailResp, error)
		AddAddress(ctx context.Context, in *AddAddressReq, opts ...grpc.CallOption) (*AddAddressResp, error)
		UpdateAddress(ctx context.Context, in *UpdateAddressReq, opts ...grpc.CallOption) (*UpdateAddressResp, error)
		DeleteAddress(ctx context.Context, in *DeleteAddressReq, opts ...grpc.CallOption) (*DeleteAddressResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 图形验证码
func (m *defaultUser) GenerateCaptcha(ctx context.Context, in *GenerateCaptchaReq, opts ...grpc.CallOption) (*GenerateCaptchaResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GenerateCaptcha(ctx, in, opts...)
}

func (m *defaultUser) VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...grpc.CallOption) (*VerifyCaptchaResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.VerifyCaptcha(ctx, in, opts...)
}

// 邮件验证码
func (m *defaultUser) SendRegisterMailCode(ctx context.Context, in *SendRegisterMailCodeReq, opts ...grpc.CallOption) (*SendMailCodeResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SendRegisterMailCode(ctx, in, opts...)
}

// 用户注册
func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 头像上传
func (m *defaultUser) UploadPreviewAvatar(ctx context.Context, in *UploadPreviewAvatarReq, opts ...grpc.CallOption) (*UploadPreviewAvatarResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UploadPreviewAvatar(ctx, in, opts...)
}

// 用户登录
func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 刷新Token
func (m *defaultUser) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// 获取用户信息
func (m *defaultUser) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// 修改用户信息
func (m *defaultUser) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

// 用户地址管理
func (m *defaultUser) GetAddressList(ctx context.Context, in *GetAddressListReq, opts ...grpc.CallOption) (*GetAddressListResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetAddressList(ctx, in, opts...)
}

func (m *defaultUser) GetAddressDetail(ctx context.Context, in *GetAddressDetailReq, opts ...grpc.CallOption) (*GetAddressDetailResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetAddressDetail(ctx, in, opts...)
}

func (m *defaultUser) AddAddress(ctx context.Context, in *AddAddressReq, opts ...grpc.CallOption) (*AddAddressResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.AddAddress(ctx, in, opts...)
}

func (m *defaultUser) UpdateAddress(ctx context.Context, in *UpdateAddressReq, opts ...grpc.CallOption) (*UpdateAddressResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateAddress(ctx, in, opts...)
}

func (m *defaultUser) DeleteAddress(ctx context.Context, in *DeleteAddressReq, opts ...grpc.CallOption) (*DeleteAddressResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteAddress(ctx, in, opts...)
}
