// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: user.proto

package userclient

import (
	"context"

	"github.com/hd2yao/ecshop/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CaptchaConfig           = user.CaptchaConfig
	DrawOptions             = user.DrawOptions
	GenerateCaptchaReq      = user.GenerateCaptchaReq
	GenerateCaptchaResp     = user.GenerateCaptchaResp
	RegisterReq             = user.RegisterReq
	RegisterResp            = user.RegisterResp
	SendMailCodeResp        = user.SendMailCodeResp
	SendRegisterMailCodeReq = user.SendRegisterMailCodeReq
	UploadPreviewAvatarReq  = user.UploadPreviewAvatarReq
	UploadPreviewAvatarResp = user.UploadPreviewAvatarResp
	UserInfo                = user.UserInfo
	VerifyCaptchaReq        = user.VerifyCaptchaReq
	VerifyCaptchaResp       = user.VerifyCaptchaResp

	User interface {
		// 图形验证码
		GenerateCaptcha(ctx context.Context, in *GenerateCaptchaReq, opts ...grpc.CallOption) (*GenerateCaptchaResp, error)
		VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...grpc.CallOption) (*VerifyCaptchaResp, error)
		// 邮件验证码
		SendRegisterMailCode(ctx context.Context, in *SendRegisterMailCodeReq, opts ...grpc.CallOption) (*SendMailCodeResp, error)
		// 用户注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		// 头像上传
		UploadPreviewAvatar(ctx context.Context, in *UploadPreviewAvatarReq, opts ...grpc.CallOption) (*UploadPreviewAvatarResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 图形验证码
func (m *defaultUser) GenerateCaptcha(ctx context.Context, in *GenerateCaptchaReq, opts ...grpc.CallOption) (*GenerateCaptchaResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GenerateCaptcha(ctx, in, opts...)
}

func (m *defaultUser) VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...grpc.CallOption) (*VerifyCaptchaResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.VerifyCaptcha(ctx, in, opts...)
}

// 邮件验证码
func (m *defaultUser) SendRegisterMailCode(ctx context.Context, in *SendRegisterMailCodeReq, opts ...grpc.CallOption) (*SendMailCodeResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.SendRegisterMailCode(ctx, in, opts...)
}

// 用户注册
func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 头像上传
func (m *defaultUser) UploadPreviewAvatar(ctx context.Context, in *UploadPreviewAvatarReq, opts ...grpc.CallOption) (*UploadPreviewAvatarResp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UploadPreviewAvatar(ctx, in, opts...)
}
