// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	"github.com/zeromicro/go-zero/rest"

	captcha "github.com/hd2yao/ecshop/user/api/internal/handler/captcha"
	mail "github.com/hd2yao/ecshop/user/api/internal/handler/mail"
	upload "github.com/hd2yao/ecshop/user/api/internal/handler/upload"
	"github.com/hd2yao/ecshop/user/api/internal/svc"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 生成验证码
				Method:  http.MethodPost,
				Path:    "/generate",
				Handler: captcha.GenerateCaptchaHandler(serverCtx),
			},
			{
				// 验证验证码
				Method:  http.MethodPost,
				Path:    "/verify",
				Handler: captcha.VerifyCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/captcha"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 发送邮件验证码
				Method:  http.MethodPost,
				Path:    "/send",
				Handler: mail.SendMailCodeHandler(serverCtx),
			},
			{
				// 验证邮件验证码
				Method:  http.MethodPost,
				Path:    "/verify",
				Handler: mail.VerifyMailCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/mail"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 上传用户头像
				Method:  http.MethodPost,
				Path:    "/avatar",
				Handler: upload.UploadAvatarHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/upload"),
	)
}
