// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	captcha "github.com/hd2yao/ecshop/user/api/internal/handler/captcha"
	"github.com/hd2yao/ecshop/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 生成验证码
				Method:  http.MethodPost,
				Path:    "/generate",
				Handler: captcha.GenerateCaptchaHandler(serverCtx),
			},
			{
				// 验证验证码
				Method:  http.MethodPost,
				Path:    "/verify",
				Handler: captcha.VerifyCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/captcha"),
	)
}
