// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	foodFieldNames          = builder.RawFieldNames(&Food{})
	foodRows                = strings.Join(foodFieldNames, ",")
	foodRowsExpectAutoSet   = strings.Join(stringx.Remove(foodFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	foodRowsWithPlaceHolder = strings.Join(stringx.Remove(foodFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFoodIdPrefix = "cache:food:id:"
)

type (
	foodModel interface {
		Insert(ctx context.Context, data *Food) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Food, error)
		Update(ctx context.Context, data *Food) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFoodModel struct {
		sqlc.CachedConn
		table string
	}

	Food struct {
		Id             int64          `db:"id"`
		UserId         int64          `db:"user_id"`         // 用户id
		FoodName       string         `db:"food_name"`       // 美食名称
		FoodDes        string         `db:"food_des"`        // 美食描述
		FoodCateTag    int64          `db:"food_cate_tag"`   // 美食分类 1、私房菜  2、家常菜  3、硬菜 4、小吃 5、开胃菜 6、甜点 7、减脂餐 8、素菜 9、养生菜
		FoodUrl        string         `db:"food_url"`        // 美食主图链接
		FoodVideoUrl   string         `db:"food_video_url"`  // 美食视频链接
		FoodTime       int64          `db:"food_time"`       // 美食制作时长  1、10分钟以内  2、10-30分钟  3、30-60分钟  4、1小时以上
		FoodDifficulty int64          `db:"food_difficulty"` // 美食制作难度 1、简单  2、一般  3、较难  4、极难
		FoodDetail     string         `db:"food_detail"`     // 美食制作详情 [{\"step\":\"步骤\", \"content\":\"步骤内容\", \"img\":\"步骤图片\"}]
		FoodList       string         `db:"food_list"`       // 美食清单
		FoodStatus     int64          `db:"food_status"`     // 美食状态 0、有效 1、删除
		FoodSkuIds     sql.NullString `db:"food_skuIds"`     // 美食关联的商品ids
		FoodCreatetime time.Time      `db:"food_createtime"` // 创建时间
		FoodUpdatetime time.Time      `db:"food_updatetime"` // 更新时间
	}
)

func newFoodModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFoodModel {
	return &defaultFoodModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`food`",
	}
}

func (m *defaultFoodModel) Delete(ctx context.Context, id int64) error {
	foodIdKey := fmt.Sprintf("%s%v", cacheFoodIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, foodIdKey)
	return err
}

func (m *defaultFoodModel) FindOne(ctx context.Context, id int64) (*Food, error) {
	foodIdKey := fmt.Sprintf("%s%v", cacheFoodIdPrefix, id)
	var resp Food
	err := m.QueryRowCtx(ctx, &resp, foodIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", foodRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFoodModel) Insert(ctx context.Context, data *Food) (sql.Result, error) {
	foodIdKey := fmt.Sprintf("%s%v", cacheFoodIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, foodRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FoodName, data.FoodDes, data.FoodCateTag, data.FoodUrl, data.FoodVideoUrl, data.FoodTime, data.FoodDifficulty, data.FoodDetail, data.FoodList, data.FoodStatus, data.FoodSkuIds, data.FoodCreatetime, data.FoodUpdatetime)
	}, foodIdKey)
	return ret, err
}

func (m *defaultFoodModel) Update(ctx context.Context, data *Food) error {
	foodIdKey := fmt.Sprintf("%s%v", cacheFoodIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, foodRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.FoodName, data.FoodDes, data.FoodCateTag, data.FoodUrl, data.FoodVideoUrl, data.FoodTime, data.FoodDifficulty, data.FoodDetail, data.FoodList, data.FoodStatus, data.FoodSkuIds, data.FoodCreatetime, data.FoodUpdatetime, data.Id)
	}, foodIdKey)
	return err
}

func (m *defaultFoodModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFoodIdPrefix, primary)
}

func (m *defaultFoodModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", foodRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFoodModel) tableName() string {
	return m.table
}
