// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type AddAddressRequest struct {
	DefaultStatus int    `json:"default_status,optional,default=0"`  // 是否默认：0否 1是
	ReceiveName   string `json:"receive_name" validate:"required"`   // 收货人姓名
	Phone         string `json:"phone" validate:"required"`          // 收货人电话
	Province      string `json:"province" validate:"required"`       // 省/直辖市
	City          string `json:"city" validate:"required"`           // 市
	Region        string `json:"region" validate:"required"`         // 区
	DetailAddress string `json:"detail_address" validate:"required"` // 详细地址
}

type AddAddressResponse struct {
	Code      int    `json:"code"`
	Message   string `json:"message"`
	AddressId int64  `json:"address_id,optional"` // 新增的地址ID
}

type CaptchaRequest struct {
	CaptchaType string       `json:"captcha_type,optional"` // string, math, chinese
	Config      DriverConfig `json:"config,optional"`
	DrawOpts    DrawOptions  `json:"draw_options,optional"`
}

type CaptchaResponse struct {
	Code      int    `json:"code"`
	Message   string `json:"message"`
	CaptchaId string `json:"captcha_id"`
	ImageData string `json:"image_data"`
	Answer    string `json:"answer,optional"` // 仅用于测试，生产环境不返回
}

type CaptchaTypeInfo struct {
	Type        string   `json:"type"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Examples    []string `json:"examples"`
}

type DeleteAddressRequest struct {
	AddressId int64 `path:"id"` // 地址ID
}

type DeleteAddressResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type DrawOptions struct {
	UseCustomDraw bool   `json:"use_custom_draw,optional"`
	DrawText      bool   `json:"draw_text,optional"`
	DrawHollow    bool   `json:"draw_hollow,optional"`
	DrawSine      bool   `json:"draw_sine,optional"`
	DrawSlimLine  int    `json:"draw_slim_line,optional"`
	DrawNoiseText string `json:"draw_noise_text,optional"`
}

type DriverConfig struct {
	Width   int    `json:"width,optional"`
	Height  int    `json:"height,optional"`
	Length  int    `json:"length,optional"`
	BgColor string `json:"bg_color,optional"`
}

type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Error   string `json:"error,optional"`
}

type GetAddressDetailRequest struct {
	AddressId int64 `path:"id"` // 地址ID
}

type GetAddressDetailResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Address UserAddress `json:"address,optional"`
}

type GetAddressListResponse struct {
	Code        int           `json:"code"`
	Message     string        `json:"message"`
	AddressList []UserAddress `json:"address_list,optional"`
}

type GetUserInfoResponse struct {
	Code     int      `json:"code"`
	Message  string   `json:"message"`
	UserInfo UserInfo `json:"user_info,optional"` // 用户信息
}

type LoginRequest struct {
	Email    string `json:"email,optional"`                     // 邮箱地址（邮箱和手机号二选一）
	Phone    string `json:"phone,optional"`                     // 手机号（邮箱和手机号二选一）
	Password string `json:"password" validate:"required,min=6"` // 密码
}

type LoginResponse struct {
	Code                  int      `json:"code"`
	Message               string   `json:"message"`
	UserId                int64    `json:"user_id,optional"`                  // 用户ID
	AccessToken           string   `json:"access_token,optional"`             // 访问令牌（2小时）
	RefreshToken          string   `json:"refresh_token,optional"`            // 刷新令牌（7天）
	AccessTokenExpireTime string   `json:"access_token_expire_time,optional"` // Access Token 过期时间（ISO 8601格式）
	UserInfo              UserInfo `json:"user_info,optional"`                // 用户信息
}

type PresetConfig struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Request     CaptchaRequest `json:"request"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token" validate:"required"` // Refresh Token
}

type RefreshTokenResponse struct {
	Code                  int    `json:"code"`
	Message               string `json:"message"`
	AccessToken           string `json:"access_token,optional"`             // 新的 Access Token
	RefreshToken          string `json:"refresh_token,optional"`            // 新的 Refresh Token
	AccessTokenExpireTime string `json:"access_token_expire_time,optional"` // Access Token 过期时间（ISO 8601格式）
}

type RegisterRequest struct {
	Email     string `json:"email" validate:"required,email"`       // 邮箱地址
	EmailCode string `json:"email_code" validate:"required,len=6"`  // 邮箱验证码
	Password  string `json:"password" validate:"required,min=6"`    // 密码
	Name      string `json:"name" validate:"required,min=2,max=32"` // 用户昵称
	Phone     string `json:"phone,optional"`                        // 手机号
	Sex       int    `json:"sex,optional,default=1"`                // 性别：0女 1男
	Avatar    string `json:"avatar,optional"`                       // 头像OSS地址
}

type RegisterResponse struct {
	Code     int      `json:"code"`
	Message  string   `json:"message"`
	UserId   int64    `json:"user_id,optional"`   // 用户ID
	UserInfo UserInfo `json:"user_info,optional"` // 用户信息
}

type SendMailCodeResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Email   string `json:"email"`
	CodeId  string `json:"code_id,optional"` // 用于测试环境返回验证码
}

type SendRegisterMailCodeRequest struct {
	CaptchaId   string `json:"captcha_id"`           // 图形验证码ID
	CaptchaCode string `json:"captcha_code"`         // 图形验证码
	Email       string `json:"email"`                // 邮箱地址
	CodeLength  int    `json:"code_length,optional"` // 验证码长度，默认6位
}

type UpdateAddressRequest struct {
	AddressId     int64  `path:"id"`                                 // 地址ID
	DefaultStatus int    `json:"default_status,optional,default=0"`  // 是否默认：0否 1是
	ReceiveName   string `json:"receive_name" validate:"required"`   // 收货人姓名
	Phone         string `json:"phone" validate:"required"`          // 收货人电话
	Province      string `json:"province" validate:"required"`       // 省/直辖市
	City          string `json:"city" validate:"required"`           // 市
	Region        string `json:"region" validate:"required"`         // 区
	DetailAddress string `json:"detail_address" validate:"required"` // 详细地址
}

type UpdateAddressResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type UpdateUserInfoRequest struct {
	Name   string `json:"name,optional"`   // 用户昵称
	Avatar string `json:"avatar,optional"` // 头像OSS地址
	Phone  string `json:"phone,optional"`  // 手机号
	Sex    int    `json:"sex,optional"`    // 性别：0女 1男
}

type UpdateUserInfoResponse struct {
	Code     int      `json:"code"`
	Message  string   `json:"message"`
	UserInfo UserInfo `json:"user_info,optional"` // 更新后的用户信息
}

type UploadPreviewAvatarResponse struct {
	Code       int    `json:"code"`
	Message    string `json:"message"`
	PreviewKey string `json:"preview_key"` // 预览标识
	PreviewUrl string `json:"preview_url"` // 预览图片
}

type UserAddress struct {
	Id            int64  `json:"id"`
	UserId        int64  `json:"user_id"`
	DefaultStatus int    `json:"default_status"` // 是否默认：0否 1是
	ReceiveName   string `json:"receive_name"`   // 收货人姓名
	Phone         string `json:"phone"`          // 收货人电话
	Province      string `json:"province"`       // 省/直辖市
	City          string `json:"city"`           // 市
	Region        string `json:"region"`         // 区
	DetailAddress string `json:"detail_address"` // 详细地址
	CreateTime    string `json:"create_time"`    // 创建时间
	UpdateTime    string `json:"update_time"`    // 更新时间
}

type UserInfo struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Avatar     string `json:"avatar"`
	Email      string `json:"email"`
	Phone      string `json:"phone"`
	Sex        int    `json:"sex"`
	Points     int    `json:"points"`
	CreateTime string `json:"create_time"`
}

type VerifyRequest struct {
	CaptchaId string `json:"captcha_id"`
	Answer    string `json:"answer"`
}

type VerifyResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Valid   bool   `json:"valid"`
}
