// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CaptchaRequest struct {
	CaptchaType string       `json:"captcha_type,optional"` // string, math, chinese
	Config      DriverConfig `json:"config,optional"`
	DrawOpts    DrawOptions  `json:"draw_options,optional"`
}

type CaptchaResponse struct {
	Code      int    `json:"code"`
	Message   string `json:"message"`
	CaptchaId string `json:"captcha_id"`
	ImageData string `json:"image_data"`
	Answer    string `json:"answer,optional"` // 仅用于测试，生产环境不返回
}

type CaptchaTypeInfo struct {
	Type        string   `json:"type"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Examples    []string `json:"examples"`
}

type DrawOptions struct {
	UseCustomDraw bool   `json:"use_custom_draw,optional"`
	DrawText      bool   `json:"draw_text,optional"`
	DrawHollow    bool   `json:"draw_hollow,optional"`
	DrawSine      bool   `json:"draw_sine,optional"`
	DrawSlimLine  int    `json:"draw_slim_line,optional"`
	DrawNoiseText string `json:"draw_noise_text,optional"`
}

type DriverConfig struct {
	Width   int    `json:"width,optional"`
	Height  int    `json:"height,optional"`
	Length  int    `json:"length,optional"`
	BgColor string `json:"bg_color,optional"`
}

type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Error   string `json:"error,optional"`
}

type PresetConfig struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Request     CaptchaRequest `json:"request"`
}

type RegisterRequest struct {
	Email     string `json:"email" validate:"required,email"`       // 邮箱地址
	EmailCode string `json:"email_code" validate:"required,len=6"`  // 邮箱验证码
	Password  string `json:"password" validate:"required,min=6"`    // 密码
	Name      string `json:"name" validate:"required,min=2,max=32"` // 用户昵称
	Phone     string `json:"phone,optional"`                        // 手机号
	Sex       int    `json:"sex,optional,default=1"`                // 性别：0女 1男
	Avatar    string `json:"avatar,optional"`                       // 头像OSS地址
}

type RegisterResponse struct {
	Code     int      `json:"code"`
	Message  string   `json:"message"`
	UserId   int64    `json:"user_id,optional"`   // 用户ID
	Token    string   `json:"token,optional"`     // 访问令牌
	UserInfo UserInfo `json:"user_info,optional"` // 用户信息
}

type SendMailCodeResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Email   string `json:"email"`
	CodeId  string `json:"code_id,optional"` // 用于测试环境返回验证码
}

type SendRegisterMailCodeRequest struct {
	CaptchaId   string `json:"captcha_id"`           // 图形验证码ID
	CaptchaCode string `json:"captcha_code"`         // 图形验证码
	Email       string `json:"email"`                // 邮箱地址
	CodeLength  int    `json:"code_length,optional"` // 验证码长度，默认6位
}

type UploadPreviewAvatarResponse struct {
	Code       int    `json:"code"`
	Message    string `json:"message"`
	PreviewKey string `json:"preview_key"` // 预览标识
	PreviewUrl string `json:"preview_url"` // 预览图片
}

type UserInfo struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Avatar     string `json:"avatar"`
	Email      string `json:"email"`
	Phone      string `json:"phone"`
	Sex        int    `json:"sex"`
	Points     int    `json:"points"`
	CreateTime string `json:"create_time"`
}

type VerifyRequest struct {
	CaptchaId string `json:"captcha_id"`
	Answer    string `json:"answer"`
}

type VerifyResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Valid   bool   `json:"valid"`
}
