// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type CaptchaRequest struct {
	CaptchaType string       `json:"captcha_type,optional"` // string, math, chinese
	Config      DriverConfig `json:"config,optional"`
	DrawOpts    DrawOptions  `json:"draw_options,optional"`
}

type CaptchaResponse struct {
	Code      int    `json:"code"`
	Message   string `json:"message"`
	CaptchaId string `json:"captcha_id"`
	ImageData string `json:"image_data"`
	Answer    string `json:"answer,optional"` // 仅用于测试，生产环境不返回
}

type CaptchaTypeInfo struct {
	Type        string   `json:"type"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Examples    []string `json:"examples"`
}

type DrawOptions struct {
	UseCustomDraw bool   `json:"use_custom_draw,optional"`
	DrawText      bool   `json:"draw_text,optional"`
	DrawHollow    bool   `json:"draw_hollow,optional"`
	DrawSine      bool   `json:"draw_sine,optional"`
	DrawSlimLine  int    `json:"draw_slim_line,optional"`
	DrawNoiseText string `json:"draw_noise_text,optional"`
}

type DriverConfig struct {
	Width   int    `json:"width,optional"`
	Height  int    `json:"height,optional"`
	Length  int    `json:"length,optional"`
	BgColor string `json:"bg_color,optional"`
}

type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Error   string `json:"error,optional"`
}

type PresetConfig struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Request     CaptchaRequest `json:"request"`
}

type SendMailCodeRequest struct {
	Email      string `json:"email"`                // 邮箱地址
	CodeLength int    `json:"code_length,optional"` // 验证码长度，默认6位
}

type SendMailCodeResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Email   string `json:"email"`
	CodeId  string `json:"code_id,optional"` // 用于测试环境返回验证码
}

type UploadAvatarRequest struct {
	UserId int64  `form:"user_id"`      // 用户ID
	Dir    string `form:"dir,optional"` // 上传目录，可选
}

type UploadResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Url     string `json:"url"`     // 文件访问URL
	CDNUrl  string `json:"cdn_url"` // CDN访问URL
	Key     string `json:"key"`     // 文件存储路径
	Size    int64  `json:"size"`    // 文件大小
}

type VerifyMailCodeRequest struct {
	Email string `json:"email"` // 邮箱地址
	Code  string `json:"code"`  // 验证码
}

type VerifyMailCodeResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Valid   bool   `json:"valid"`
}

type VerifyRequest struct {
	CaptchaId string `json:"captcha_id"`
	Answer    string `json:"answer"`
}

type VerifyResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Valid   bool   `json:"valid"`
}
