// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: rpc/home.proto

package home

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 食谱详情
type RecipesInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RecipesName        string                 `protobuf:"bytes,2,opt,name=recipes_name,json=recipesName,proto3" json:"recipes_name,omitempty"`
	RecipesUrl         string                 `protobuf:"bytes,3,opt,name=recipes_url,json=recipesUrl,proto3" json:"recipes_url,omitempty"`
	RecipesUserName    string                 `protobuf:"bytes,4,opt,name=recipes_user_name,json=recipesUserName,proto3" json:"recipes_user_name,omitempty"`
	RecipesUserAvatar  string                 `protobuf:"bytes,5,opt,name=recipes_user_avatar,json=recipesUserAvatar,proto3" json:"recipes_user_avatar,omitempty"`
	RecipesDescription string                 `protobuf:"bytes,6,opt,name=recipes_description,json=recipesDescription,proto3" json:"recipes_description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecipesInfo) Reset() {
	*x = RecipesInfo{}
	mi := &file_rpc_home_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipesInfo) ProtoMessage() {}

func (x *RecipesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_home_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipesInfo.ProtoReflect.Descriptor instead.
func (*RecipesInfo) Descriptor() ([]byte, []int) {
	return file_rpc_home_proto_rawDescGZIP(), []int{0}
}

func (x *RecipesInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecipesInfo) GetRecipesName() string {
	if x != nil {
		return x.RecipesName
	}
	return ""
}

func (x *RecipesInfo) GetRecipesUrl() string {
	if x != nil {
		return x.RecipesUrl
	}
	return ""
}

func (x *RecipesInfo) GetRecipesUserName() string {
	if x != nil {
		return x.RecipesUserName
	}
	return ""
}

func (x *RecipesInfo) GetRecipesUserAvatar() string {
	if x != nil {
		return x.RecipesUserAvatar
	}
	return ""
}

func (x *RecipesInfo) GetRecipesDescription() string {
	if x != nil {
		return x.RecipesDescription
	}
	return ""
}

// 生成缓存
type GenerateFeedCacheReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFeedCacheReq) Reset() {
	*x = GenerateFeedCacheReq{}
	mi := &file_rpc_home_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFeedCacheReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFeedCacheReq) ProtoMessage() {}

func (x *GenerateFeedCacheReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_home_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFeedCacheReq.ProtoReflect.Descriptor instead.
func (*GenerateFeedCacheReq) Descriptor() ([]byte, []int) {
	return file_rpc_home_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateFeedCacheReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *GenerateFeedCacheReq) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type GenerateFeedCacheResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FeedVersion   string                 `protobuf:"bytes,3,opt,name=feed_version,json=feedVersion,proto3" json:"feed_version,omitempty"`
	RecipesList   []*RecipesInfo         `protobuf:"bytes,4,rep,name=recipes_list,json=recipesList,proto3" json:"recipes_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateFeedCacheResp) Reset() {
	*x = GenerateFeedCacheResp{}
	mi := &file_rpc_home_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateFeedCacheResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateFeedCacheResp) ProtoMessage() {}

func (x *GenerateFeedCacheResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_home_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateFeedCacheResp.ProtoReflect.Descriptor instead.
func (*GenerateFeedCacheResp) Descriptor() ([]byte, []int) {
	return file_rpc_home_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateFeedCacheResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenerateFeedCacheResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateFeedCacheResp) GetFeedVersion() string {
	if x != nil {
		return x.FeedVersion
	}
	return ""
}

func (x *GenerateFeedCacheResp) GetRecipesList() []*RecipesInfo {
	if x != nil {
		return x.RecipesList
	}
	return nil
}

// 查询 feed
type HomeFeedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FeedVersion   string                 `protobuf:"bytes,2,opt,name=feed_version,json=feedVersion,proto3" json:"feed_version,omitempty"`
	PullRefresh   bool                   `protobuf:"varint,3,opt,name=pull_refresh,json=pullRefresh,proto3" json:"pull_refresh,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeFeedReq) Reset() {
	*x = HomeFeedReq{}
	mi := &file_rpc_home_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeFeedReq) ProtoMessage() {}

func (x *HomeFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_home_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeFeedReq.ProtoReflect.Descriptor instead.
func (*HomeFeedReq) Descriptor() ([]byte, []int) {
	return file_rpc_home_proto_rawDescGZIP(), []int{3}
}

func (x *HomeFeedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HomeFeedReq) GetFeedVersion() string {
	if x != nil {
		return x.FeedVersion
	}
	return ""
}

func (x *HomeFeedReq) GetPullRefresh() bool {
	if x != nil {
		return x.PullRefresh
	}
	return false
}

func (x *HomeFeedReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *HomeFeedReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type HomeFeedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FeedVersion   string                 `protobuf:"bytes,3,opt,name=feed_version,json=feedVersion,proto3" json:"feed_version,omitempty"`
	CurrPage      int32                  `protobuf:"varint,4,opt,name=curr_page,json=currPage,proto3" json:"curr_page,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	RecipesList   []*RecipesInfo         `protobuf:"bytes,6,rep,name=recipes_list,json=recipesList,proto3" json:"recipes_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeFeedResp) Reset() {
	*x = HomeFeedResp{}
	mi := &file_rpc_home_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeFeedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeFeedResp) ProtoMessage() {}

func (x *HomeFeedResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_home_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeFeedResp.ProtoReflect.Descriptor instead.
func (*HomeFeedResp) Descriptor() ([]byte, []int) {
	return file_rpc_home_proto_rawDescGZIP(), []int{4}
}

func (x *HomeFeedResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HomeFeedResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HomeFeedResp) GetFeedVersion() string {
	if x != nil {
		return x.FeedVersion
	}
	return ""
}

func (x *HomeFeedResp) GetCurrPage() int32 {
	if x != nil {
		return x.CurrPage
	}
	return 0
}

func (x *HomeFeedResp) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *HomeFeedResp) GetRecipesList() []*RecipesInfo {
	if x != nil {
		return x.RecipesList
	}
	return nil
}

var File_rpc_home_proto protoreflect.FileDescriptor

const file_rpc_home_proto_rawDesc = "" +
	"\n" +
	"\x0erpc/home.proto\x12\x04home\"\xee\x01\n" +
	"\vRecipesInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\frecipes_name\x18\x02 \x01(\tR\vrecipesName\x12\x1f\n" +
	"\vrecipes_url\x18\x03 \x01(\tR\n" +
	"recipesUrl\x12*\n" +
	"\x11recipes_user_name\x18\x04 \x01(\tR\x0frecipesUserName\x12.\n" +
	"\x13recipes_user_avatar\x18\x05 \x01(\tR\x11recipesUserAvatar\x12/\n" +
	"\x13recipes_description\x18\x06 \x01(\tR\x12recipesDescription\"H\n" +
	"\x14GenerateFeedCacheReq\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x9e\x01\n" +
	"\x15GenerateFeedCacheResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\ffeed_version\x18\x03 \x01(\tR\vfeedVersion\x124\n" +
	"\frecipes_list\x18\x04 \x03(\v2\x11.home.RecipesInfoR\vrecipesList\"\x9d\x01\n" +
	"\vHomeFeedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\ffeed_version\x18\x02 \x01(\tR\vfeedVersion\x12!\n" +
	"\fpull_refresh\x18\x03 \x01(\bR\vpullRefresh\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xd6\x01\n" +
	"\fHomeFeedResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\ffeed_version\x18\x03 \x01(\tR\vfeedVersion\x12\x1b\n" +
	"\tcurr_page\x18\x04 \x01(\x05R\bcurrPage\x12\"\n" +
	"\rhas_next_page\x18\x05 \x01(\bR\vhasNextPage\x124\n" +
	"\frecipes_list\x18\x06 \x03(\v2\x11.home.RecipesInfoR\vrecipesList2\x8a\x01\n" +
	"\x04Home\x12L\n" +
	"\x11GenerateFeedCache\x12\x1a.home.GenerateFeedCacheReq\x1a\x1b.home.GenerateFeedCacheResp\x124\n" +
	"\vGetHomeFeed\x12\x11.home.HomeFeedReq\x1a\x12.home.HomeFeedRespB\bZ\x06./homeb\x06proto3"

var (
	file_rpc_home_proto_rawDescOnce sync.Once
	file_rpc_home_proto_rawDescData []byte
)

func file_rpc_home_proto_rawDescGZIP() []byte {
	file_rpc_home_proto_rawDescOnce.Do(func() {
		file_rpc_home_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_home_proto_rawDesc), len(file_rpc_home_proto_rawDesc)))
	})
	return file_rpc_home_proto_rawDescData
}

var file_rpc_home_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpc_home_proto_goTypes = []any{
	(*RecipesInfo)(nil),           // 0: home.RecipesInfo
	(*GenerateFeedCacheReq)(nil),  // 1: home.GenerateFeedCacheReq
	(*GenerateFeedCacheResp)(nil), // 2: home.GenerateFeedCacheResp
	(*HomeFeedReq)(nil),           // 3: home.HomeFeedReq
	(*HomeFeedResp)(nil),          // 4: home.HomeFeedResp
}
var file_rpc_home_proto_depIdxs = []int32{
	0, // 0: home.GenerateFeedCacheResp.recipes_list:type_name -> home.RecipesInfo
	0, // 1: home.HomeFeedResp.recipes_list:type_name -> home.RecipesInfo
	1, // 2: home.Home.GenerateFeedCache:input_type -> home.GenerateFeedCacheReq
	3, // 3: home.Home.GetHomeFeed:input_type -> home.HomeFeedReq
	2, // 4: home.Home.GenerateFeedCache:output_type -> home.GenerateFeedCacheResp
	4, // 5: home.Home.GetHomeFeed:output_type -> home.HomeFeedResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_home_proto_init() }
func file_rpc_home_proto_init() {
	if File_rpc_home_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_home_proto_rawDesc), len(file_rpc_home_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_home_proto_goTypes,
		DependencyIndexes: file_rpc_home_proto_depIdxs,
		MessageInfos:      file_rpc_home_proto_msgTypes,
	}.Build()
	File_rpc_home_proto = out.File
	file_rpc_home_proto_goTypes = nil
	file_rpc_home_proto_depIdxs = nil
}
