// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: rpc/home.proto

package home

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Home_GenerateFeedCache_FullMethodName = "/home.Home/GenerateFeedCache"
	Home_GetHomeFeed_FullMethodName       = "/home.Home/GetHomeFeed"
)

// HomeClient is the client API for Home service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 首页Feed服务
type HomeClient interface {
	// 生成 feed 食谱缓存
	GenerateFeedCache(ctx context.Context, in *GenerateFeedCacheReq, opts ...grpc.CallOption) (*GenerateFeedCacheResp, error)
	// 获取首页 feed 食谱列表
	GetHomeFeed(ctx context.Context, in *HomeFeedReq, opts ...grpc.CallOption) (*HomeFeedResp, error)
}

type homeClient struct {
	cc grpc.ClientConnInterface
}

func NewHomeClient(cc grpc.ClientConnInterface) HomeClient {
	return &homeClient{cc}
}

func (c *homeClient) GenerateFeedCache(ctx context.Context, in *GenerateFeedCacheReq, opts ...grpc.CallOption) (*GenerateFeedCacheResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateFeedCacheResp)
	err := c.cc.Invoke(ctx, Home_GenerateFeedCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeClient) GetHomeFeed(ctx context.Context, in *HomeFeedReq, opts ...grpc.CallOption) (*HomeFeedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeFeedResp)
	err := c.cc.Invoke(ctx, Home_GetHomeFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomeServer is the server API for Home service.
// All implementations must embed UnimplementedHomeServer
// for forward compatibility.
//
// 首页Feed服务
type HomeServer interface {
	// 生成 feed 食谱缓存
	GenerateFeedCache(context.Context, *GenerateFeedCacheReq) (*GenerateFeedCacheResp, error)
	// 获取首页 feed 食谱列表
	GetHomeFeed(context.Context, *HomeFeedReq) (*HomeFeedResp, error)
	mustEmbedUnimplementedHomeServer()
}

// UnimplementedHomeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHomeServer struct{}

func (UnimplementedHomeServer) GenerateFeedCache(context.Context, *GenerateFeedCacheReq) (*GenerateFeedCacheResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateFeedCache not implemented")
}
func (UnimplementedHomeServer) GetHomeFeed(context.Context, *HomeFeedReq) (*HomeFeedResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHomeFeed not implemented")
}
func (UnimplementedHomeServer) mustEmbedUnimplementedHomeServer() {}
func (UnimplementedHomeServer) testEmbeddedByValue()              {}

// UnsafeHomeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HomeServer will
// result in compilation errors.
type UnsafeHomeServer interface {
	mustEmbedUnimplementedHomeServer()
}

func RegisterHomeServer(s grpc.ServiceRegistrar, srv HomeServer) {
	// If the following call pancis, it indicates UnimplementedHomeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Home_ServiceDesc, srv)
}

func _Home_GenerateFeedCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateFeedCacheReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServer).GenerateFeedCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Home_GenerateFeedCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServer).GenerateFeedCache(ctx, req.(*GenerateFeedCacheReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Home_GetHomeFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeFeedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeServer).GetHomeFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Home_GetHomeFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeServer).GetHomeFeed(ctx, req.(*HomeFeedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Home_ServiceDesc is the grpc.ServiceDesc for Home service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Home_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "home.Home",
	HandlerType: (*HomeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateFeedCache",
			Handler:    _Home_GenerateFeedCache_Handler,
		},
		{
			MethodName: "GetHomeFeed",
			Handler:    _Home_GetHomeFeed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/home.proto",
}
