// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: rpc/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 图形验证码相关
type GenerateCaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaType   string                 `protobuf:"bytes,1,opt,name=captcha_type,json=captchaType,proto3" json:"captcha_type,omitempty"`
	Config        *CaptchaConfig         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	DrawOpts      *DrawOptions           `protobuf:"bytes,3,opt,name=draw_opts,json=drawOpts,proto3" json:"draw_opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCaptchaReq) Reset() {
	*x = GenerateCaptchaReq{}
	mi := &file_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCaptchaReq) ProtoMessage() {}

func (x *GenerateCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCaptchaReq.ProtoReflect.Descriptor instead.
func (*GenerateCaptchaReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateCaptchaReq) GetCaptchaType() string {
	if x != nil {
		return x.CaptchaType
	}
	return ""
}

func (x *GenerateCaptchaReq) GetConfig() *CaptchaConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GenerateCaptchaReq) GetDrawOpts() *DrawOptions {
	if x != nil {
		return x.DrawOpts
	}
	return nil
}

type GenerateCaptchaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CaptchaId     string                 `protobuf:"bytes,3,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	ImageData     string                 `protobuf:"bytes,4,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Answer        string                 `protobuf:"bytes,5,opt,name=answer,proto3" json:"answer,omitempty"` // 测试环境使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCaptchaResp) Reset() {
	*x = GenerateCaptchaResp{}
	mi := &file_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCaptchaResp) ProtoMessage() {}

func (x *GenerateCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCaptchaResp.ProtoReflect.Descriptor instead.
func (*GenerateCaptchaResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateCaptchaResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenerateCaptchaResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateCaptchaResp) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *GenerateCaptchaResp) GetImageData() string {
	if x != nil {
		return x.ImageData
	}
	return ""
}

func (x *GenerateCaptchaResp) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type VerifyCaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaReq) Reset() {
	*x = VerifyCaptchaReq{}
	mi := &file_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaReq) ProtoMessage() {}

func (x *VerifyCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaReq.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCaptchaReq) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *VerifyCaptchaReq) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type VerifyCaptchaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaResp) Reset() {
	*x = VerifyCaptchaResp{}
	mi := &file_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaResp) ProtoMessage() {}

func (x *VerifyCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaResp.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCaptchaResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VerifyCaptchaResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyCaptchaResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// 邮件验证码相关
type SendMailCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CodeLength    int32                  `protobuf:"varint,2,opt,name=code_length,json=codeLength,proto3" json:"code_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailCodeReq) Reset() {
	*x = SendMailCodeReq{}
	mi := &file_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailCodeReq) ProtoMessage() {}

func (x *SendMailCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailCodeReq.ProtoReflect.Descriptor instead.
func (*SendMailCodeReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *SendMailCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendMailCodeReq) GetCodeLength() int32 {
	if x != nil {
		return x.CodeLength
	}
	return 0
}

type SendMailCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CodeId        string                 `protobuf:"bytes,4,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"` // 测试环境返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailCodeResp) Reset() {
	*x = SendMailCodeResp{}
	mi := &file_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailCodeResp) ProtoMessage() {}

func (x *SendMailCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailCodeResp.ProtoReflect.Descriptor instead.
func (*SendMailCodeResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *SendMailCodeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendMailCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMailCodeResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendMailCodeResp) GetCodeId() string {
	if x != nil {
		return x.CodeId
	}
	return ""
}

type VerifyMailCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMailCodeReq) Reset() {
	*x = VerifyMailCodeReq{}
	mi := &file_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMailCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMailCodeReq) ProtoMessage() {}

func (x *VerifyMailCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMailCodeReq.ProtoReflect.Descriptor instead.
func (*VerifyMailCodeReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyMailCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyMailCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifyMailCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyMailCodeResp) Reset() {
	*x = VerifyMailCodeResp{}
	mi := &file_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyMailCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMailCodeResp) ProtoMessage() {}

func (x *VerifyMailCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMailCodeResp.ProtoReflect.Descriptor instead.
func (*VerifyMailCodeResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyMailCodeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VerifyMailCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyMailCodeResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// 辅助结构
type CaptchaConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	BgColor       string                 `protobuf:"bytes,4,opt,name=bg_color,json=bgColor,proto3" json:"bg_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaConfig) Reset() {
	*x = CaptchaConfig{}
	mi := &file_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaConfig) ProtoMessage() {}

func (x *CaptchaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaConfig.ProtoReflect.Descriptor instead.
func (*CaptchaConfig) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *CaptchaConfig) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CaptchaConfig) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CaptchaConfig) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *CaptchaConfig) GetBgColor() string {
	if x != nil {
		return x.BgColor
	}
	return ""
}

type DrawOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UseCustomDraw bool                   `protobuf:"varint,1,opt,name=use_custom_draw,json=useCustomDraw,proto3" json:"use_custom_draw,omitempty"`
	DrawText      bool                   `protobuf:"varint,2,opt,name=draw_text,json=drawText,proto3" json:"draw_text,omitempty"`
	DrawHollow    bool                   `protobuf:"varint,3,opt,name=draw_hollow,json=drawHollow,proto3" json:"draw_hollow,omitempty"`
	DrawSine      bool                   `protobuf:"varint,4,opt,name=draw_sine,json=drawSine,proto3" json:"draw_sine,omitempty"`
	DrawSlimLine  int32                  `protobuf:"varint,5,opt,name=draw_slim_line,json=drawSlimLine,proto3" json:"draw_slim_line,omitempty"`
	DrawNoiseText string                 `protobuf:"bytes,6,opt,name=draw_noise_text,json=drawNoiseText,proto3" json:"draw_noise_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawOptions) Reset() {
	*x = DrawOptions{}
	mi := &file_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawOptions) ProtoMessage() {}

func (x *DrawOptions) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawOptions.ProtoReflect.Descriptor instead.
func (*DrawOptions) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{9}
}

func (x *DrawOptions) GetUseCustomDraw() bool {
	if x != nil {
		return x.UseCustomDraw
	}
	return false
}

func (x *DrawOptions) GetDrawText() bool {
	if x != nil {
		return x.DrawText
	}
	return false
}

func (x *DrawOptions) GetDrawHollow() bool {
	if x != nil {
		return x.DrawHollow
	}
	return false
}

func (x *DrawOptions) GetDrawSine() bool {
	if x != nil {
		return x.DrawSine
	}
	return false
}

func (x *DrawOptions) GetDrawSlimLine() int32 {
	if x != nil {
		return x.DrawSlimLine
	}
	return 0
}

func (x *DrawOptions) GetDrawNoiseText() string {
	if x != nil {
		return x.DrawNoiseText
	}
	return ""
}

// 头像上传相关
type UploadAvatarReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`  // 文件数据
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`                  // 文件名
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"` // 文件大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarReq) Reset() {
	*x = UploadAvatarReq{}
	mi := &file_rpc_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarReq) ProtoMessage() {}

func (x *UploadAvatarReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarReq.ProtoReflect.Descriptor instead.
func (*UploadAvatarReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{10}
}

func (x *UploadAvatarReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadAvatarReq) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadAvatarReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadAvatarReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadAvatarResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                     // 文件访问URL
	CdnUrl        string                 `protobuf:"bytes,4,opt,name=cdn_url,json=cdnUrl,proto3" json:"cdn_url,omitempty"` // CDN访问URL
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`                     // 文件存储路径
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`                  // 文件大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAvatarResp) Reset() {
	*x = UploadAvatarResp{}
	mi := &file_rpc_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResp) ProtoMessage() {}

func (x *UploadAvatarResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResp.ProtoReflect.Descriptor instead.
func (*UploadAvatarResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{11}
}

func (x *UploadAvatarResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadAvatarResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadAvatarResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadAvatarResp) GetCdnUrl() string {
	if x != nil {
		return x.CdnUrl
	}
	return ""
}

func (x *UploadAvatarResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UploadAvatarResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_rpc_user_proto protoreflect.FileDescriptor

const file_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x0erpc/user.proto\x12\x04user\"\x94\x01\n" +
	"\x12GenerateCaptchaReq\x12!\n" +
	"\fcaptcha_type\x18\x01 \x01(\tR\vcaptchaType\x12+\n" +
	"\x06config\x18\x02 \x01(\v2\x13.user.CaptchaConfigR\x06config\x12.\n" +
	"\tdraw_opts\x18\x03 \x01(\v2\x11.user.DrawOptionsR\bdrawOpts\"\x99\x01\n" +
	"\x13GenerateCaptchaResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x03 \x01(\tR\tcaptchaId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x04 \x01(\tR\timageData\x12\x16\n" +
	"\x06answer\x18\x05 \x01(\tR\x06answer\"I\n" +
	"\x10VerifyCaptchaReq\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x01 \x01(\tR\tcaptchaId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\"W\n" +
	"\x11VerifyCaptchaResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"H\n" +
	"\x0fSendMailCodeReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1f\n" +
	"\vcode_length\x18\x02 \x01(\x05R\n" +
	"codeLength\"o\n" +
	"\x10SendMailCodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x17\n" +
	"\acode_id\x18\x04 \x01(\tR\x06codeId\"=\n" +
	"\x11VerifyMailCodeReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"X\n" +
	"\x12VerifyMailCodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"p\n" +
	"\rCaptchaConfig\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x12\x19\n" +
	"\bbg_color\x18\x04 \x01(\tR\abgColor\"\xde\x01\n" +
	"\vDrawOptions\x12&\n" +
	"\x0fuse_custom_draw\x18\x01 \x01(\bR\ruseCustomDraw\x12\x1b\n" +
	"\tdraw_text\x18\x02 \x01(\bR\bdrawText\x12\x1f\n" +
	"\vdraw_hollow\x18\x03 \x01(\bR\n" +
	"drawHollow\x12\x1b\n" +
	"\tdraw_sine\x18\x04 \x01(\bR\bdrawSine\x12$\n" +
	"\x0edraw_slim_line\x18\x05 \x01(\x05R\fdrawSlimLine\x12&\n" +
	"\x0fdraw_noise_text\x18\x06 \x01(\tR\rdrawNoiseText\"\x80\x01\n" +
	"\x0fUploadAvatarReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\"\x91\x01\n" +
	"\x10UploadAvatarResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x17\n" +
	"\acdn_url\x18\x04 \x01(\tR\x06cdnUrl\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size2\xd3\x02\n" +
	"\x04User\x12F\n" +
	"\x0fGenerateCaptcha\x12\x18.user.GenerateCaptchaReq\x1a\x19.user.GenerateCaptchaResp\x12@\n" +
	"\rVerifyCaptcha\x12\x16.user.VerifyCaptchaReq\x1a\x17.user.VerifyCaptchaResp\x12=\n" +
	"\fSendMailCode\x12\x15.user.SendMailCodeReq\x1a\x16.user.SendMailCodeResp\x12C\n" +
	"\x0eVerifyMailCode\x12\x17.user.VerifyMailCodeReq\x1a\x18.user.VerifyMailCodeResp\x12=\n" +
	"\fUploadAvatar\x12\x15.user.UploadAvatarReq\x1a\x16.user.UploadAvatarRespB\bZ\x06./userb\x06proto3"

var (
	file_rpc_user_proto_rawDescOnce sync.Once
	file_rpc_user_proto_rawDescData []byte
)

func file_rpc_user_proto_rawDescGZIP() []byte {
	file_rpc_user_proto_rawDescOnce.Do(func() {
		file_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_user_proto_rawDesc), len(file_rpc_user_proto_rawDesc)))
	})
	return file_rpc_user_proto_rawDescData
}

var file_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_rpc_user_proto_goTypes = []any{
	(*GenerateCaptchaReq)(nil),  // 0: user.GenerateCaptchaReq
	(*GenerateCaptchaResp)(nil), // 1: user.GenerateCaptchaResp
	(*VerifyCaptchaReq)(nil),    // 2: user.VerifyCaptchaReq
	(*VerifyCaptchaResp)(nil),   // 3: user.VerifyCaptchaResp
	(*SendMailCodeReq)(nil),     // 4: user.SendMailCodeReq
	(*SendMailCodeResp)(nil),    // 5: user.SendMailCodeResp
	(*VerifyMailCodeReq)(nil),   // 6: user.VerifyMailCodeReq
	(*VerifyMailCodeResp)(nil),  // 7: user.VerifyMailCodeResp
	(*CaptchaConfig)(nil),       // 8: user.CaptchaConfig
	(*DrawOptions)(nil),         // 9: user.DrawOptions
	(*UploadAvatarReq)(nil),     // 10: user.UploadAvatarReq
	(*UploadAvatarResp)(nil),    // 11: user.UploadAvatarResp
}
var file_rpc_user_proto_depIdxs = []int32{
	8,  // 0: user.GenerateCaptchaReq.config:type_name -> user.CaptchaConfig
	9,  // 1: user.GenerateCaptchaReq.draw_opts:type_name -> user.DrawOptions
	0,  // 2: user.User.GenerateCaptcha:input_type -> user.GenerateCaptchaReq
	2,  // 3: user.User.VerifyCaptcha:input_type -> user.VerifyCaptchaReq
	4,  // 4: user.User.SendMailCode:input_type -> user.SendMailCodeReq
	6,  // 5: user.User.VerifyMailCode:input_type -> user.VerifyMailCodeReq
	10, // 6: user.User.UploadAvatar:input_type -> user.UploadAvatarReq
	1,  // 7: user.User.GenerateCaptcha:output_type -> user.GenerateCaptchaResp
	3,  // 8: user.User.VerifyCaptcha:output_type -> user.VerifyCaptchaResp
	5,  // 9: user.User.SendMailCode:output_type -> user.SendMailCodeResp
	7,  // 10: user.User.VerifyMailCode:output_type -> user.VerifyMailCodeResp
	11, // 11: user.User.UploadAvatar:output_type -> user.UploadAvatarResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_user_proto_init() }
func file_rpc_user_proto_init() {
	if File_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_user_proto_rawDesc), len(file_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_user_proto_goTypes,
		DependencyIndexes: file_rpc_user_proto_depIdxs,
		MessageInfos:      file_rpc_user_proto_msgTypes,
	}.Build()
	File_rpc_user_proto = out.File
	file_rpc_user_proto_goTypes = nil
	file_rpc_user_proto_depIdxs = nil
}
