// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: rpc/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 图形验证码相关
type GenerateCaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaType   string                 `protobuf:"bytes,1,opt,name=captcha_type,json=captchaType,proto3" json:"captcha_type,omitempty"`
	Config        *CaptchaConfig         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	DrawOpts      *DrawOptions           `protobuf:"bytes,3,opt,name=draw_opts,json=drawOpts,proto3" json:"draw_opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCaptchaReq) Reset() {
	*x = GenerateCaptchaReq{}
	mi := &file_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCaptchaReq) ProtoMessage() {}

func (x *GenerateCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCaptchaReq.ProtoReflect.Descriptor instead.
func (*GenerateCaptchaReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateCaptchaReq) GetCaptchaType() string {
	if x != nil {
		return x.CaptchaType
	}
	return ""
}

func (x *GenerateCaptchaReq) GetConfig() *CaptchaConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GenerateCaptchaReq) GetDrawOpts() *DrawOptions {
	if x != nil {
		return x.DrawOpts
	}
	return nil
}

type GenerateCaptchaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CaptchaId     string                 `protobuf:"bytes,3,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	ImageData     string                 `protobuf:"bytes,4,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Answer        string                 `protobuf:"bytes,5,opt,name=answer,proto3" json:"answer,omitempty"` // 测试环境使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCaptchaResp) Reset() {
	*x = GenerateCaptchaResp{}
	mi := &file_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCaptchaResp) ProtoMessage() {}

func (x *GenerateCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCaptchaResp.ProtoReflect.Descriptor instead.
func (*GenerateCaptchaResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateCaptchaResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenerateCaptchaResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateCaptchaResp) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *GenerateCaptchaResp) GetImageData() string {
	if x != nil {
		return x.ImageData
	}
	return ""
}

func (x *GenerateCaptchaResp) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type VerifyCaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaReq) Reset() {
	*x = VerifyCaptchaReq{}
	mi := &file_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaReq) ProtoMessage() {}

func (x *VerifyCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaReq.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCaptchaReq) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *VerifyCaptchaReq) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type VerifyCaptchaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaResp) Reset() {
	*x = VerifyCaptchaResp{}
	mi := &file_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaResp) ProtoMessage() {}

func (x *VerifyCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaResp.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCaptchaResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VerifyCaptchaResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyCaptchaResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// 邮件验证码相关
type SendMailCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CodeId        string                 `protobuf:"bytes,4,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"` // 测试环境返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailCodeResp) Reset() {
	*x = SendMailCodeResp{}
	mi := &file_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailCodeResp) ProtoMessage() {}

func (x *SendMailCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailCodeResp.ProtoReflect.Descriptor instead.
func (*SendMailCodeResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *SendMailCodeResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendMailCodeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMailCodeResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendMailCodeResp) GetCodeId() string {
	if x != nil {
		return x.CodeId
	}
	return ""
}

// 注册时发送邮件验证码
type SendRegisterMailCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=captcha_id,json=captchaId,proto3" json:"captcha_id,omitempty"`
	CaptchaCode   string                 `protobuf:"bytes,2,opt,name=captcha_code,json=captchaCode,proto3" json:"captcha_code,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CodeLength    int32                  `protobuf:"varint,4,opt,name=code_length,json=codeLength,proto3" json:"code_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRegisterMailCodeReq) Reset() {
	*x = SendRegisterMailCodeReq{}
	mi := &file_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRegisterMailCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRegisterMailCodeReq) ProtoMessage() {}

func (x *SendRegisterMailCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRegisterMailCodeReq.ProtoReflect.Descriptor instead.
func (*SendRegisterMailCodeReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *SendRegisterMailCodeReq) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *SendRegisterMailCodeReq) GetCaptchaCode() string {
	if x != nil {
		return x.CaptchaCode
	}
	return ""
}

func (x *SendRegisterMailCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendRegisterMailCodeReq) GetCodeLength() int32 {
	if x != nil {
		return x.CodeLength
	}
	return 0
}

// 用户注册相关
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	EmailCode     string                 `protobuf:"bytes,2,opt,name=email_code,json=emailCode,proto3" json:"email_code,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Sex           int32                  `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"` // 头像OSS地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterReq) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *RegisterReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,5,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Sex           int32                  `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Points        int32                  `protobuf:"varint,7,opt,name=points,proto3" json:"points,omitempty"`
	CreateTime    string                 `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfo) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *UserInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// 辅助结构
type CaptchaConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	BgColor       string                 `protobuf:"bytes,4,opt,name=bg_color,json=bgColor,proto3" json:"bg_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaConfig) Reset() {
	*x = CaptchaConfig{}
	mi := &file_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaConfig) ProtoMessage() {}

func (x *CaptchaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaConfig.ProtoReflect.Descriptor instead.
func (*CaptchaConfig) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{9}
}

func (x *CaptchaConfig) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CaptchaConfig) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CaptchaConfig) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *CaptchaConfig) GetBgColor() string {
	if x != nil {
		return x.BgColor
	}
	return ""
}

type DrawOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UseCustomDraw bool                   `protobuf:"varint,1,opt,name=use_custom_draw,json=useCustomDraw,proto3" json:"use_custom_draw,omitempty"`
	DrawText      bool                   `protobuf:"varint,2,opt,name=draw_text,json=drawText,proto3" json:"draw_text,omitempty"`
	DrawHollow    bool                   `protobuf:"varint,3,opt,name=draw_hollow,json=drawHollow,proto3" json:"draw_hollow,omitempty"`
	DrawSine      bool                   `protobuf:"varint,4,opt,name=draw_sine,json=drawSine,proto3" json:"draw_sine,omitempty"`
	DrawSlimLine  int32                  `protobuf:"varint,5,opt,name=draw_slim_line,json=drawSlimLine,proto3" json:"draw_slim_line,omitempty"`
	DrawNoiseText string                 `protobuf:"bytes,6,opt,name=draw_noise_text,json=drawNoiseText,proto3" json:"draw_noise_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawOptions) Reset() {
	*x = DrawOptions{}
	mi := &file_rpc_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawOptions) ProtoMessage() {}

func (x *DrawOptions) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawOptions.ProtoReflect.Descriptor instead.
func (*DrawOptions) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{10}
}

func (x *DrawOptions) GetUseCustomDraw() bool {
	if x != nil {
		return x.UseCustomDraw
	}
	return false
}

func (x *DrawOptions) GetDrawText() bool {
	if x != nil {
		return x.DrawText
	}
	return false
}

func (x *DrawOptions) GetDrawHollow() bool {
	if x != nil {
		return x.DrawHollow
	}
	return false
}

func (x *DrawOptions) GetDrawSine() bool {
	if x != nil {
		return x.DrawSine
	}
	return false
}

func (x *DrawOptions) GetDrawSlimLine() int32 {
	if x != nil {
		return x.DrawSlimLine
	}
	return 0
}

func (x *DrawOptions) GetDrawNoiseText() string {
	if x != nil {
		return x.DrawNoiseText
	}
	return ""
}

// 头像管理相关
type UploadPreviewAvatarReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileData      []byte                 `protobuf:"bytes,1,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`  // 文件数据
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`                  // 文件名
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"` // 文件大小
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPreviewAvatarReq) Reset() {
	*x = UploadPreviewAvatarReq{}
	mi := &file_rpc_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPreviewAvatarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPreviewAvatarReq) ProtoMessage() {}

func (x *UploadPreviewAvatarReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPreviewAvatarReq.ProtoReflect.Descriptor instead.
func (*UploadPreviewAvatarReq) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{11}
}

func (x *UploadPreviewAvatarReq) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadPreviewAvatarReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadPreviewAvatarReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type UploadPreviewAvatarResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PreviewKey    string                 `protobuf:"bytes,3,opt,name=preview_key,json=previewKey,proto3" json:"preview_key,omitempty"` // 预览标识
	PreviewUrl    string                 `protobuf:"bytes,4,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"` // 预览图片URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPreviewAvatarResp) Reset() {
	*x = UploadPreviewAvatarResp{}
	mi := &file_rpc_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPreviewAvatarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPreviewAvatarResp) ProtoMessage() {}

func (x *UploadPreviewAvatarResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPreviewAvatarResp.ProtoReflect.Descriptor instead.
func (*UploadPreviewAvatarResp) Descriptor() ([]byte, []int) {
	return file_rpc_user_proto_rawDescGZIP(), []int{12}
}

func (x *UploadPreviewAvatarResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadPreviewAvatarResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadPreviewAvatarResp) GetPreviewKey() string {
	if x != nil {
		return x.PreviewKey
	}
	return ""
}

func (x *UploadPreviewAvatarResp) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

var File_rpc_user_proto protoreflect.FileDescriptor

const file_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x0erpc/user.proto\x12\x04user\"\x94\x01\n" +
	"\x12GenerateCaptchaReq\x12!\n" +
	"\fcaptcha_type\x18\x01 \x01(\tR\vcaptchaType\x12+\n" +
	"\x06config\x18\x02 \x01(\v2\x13.user.CaptchaConfigR\x06config\x12.\n" +
	"\tdraw_opts\x18\x03 \x01(\v2\x11.user.DrawOptionsR\bdrawOpts\"\x99\x01\n" +
	"\x13GenerateCaptchaResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x03 \x01(\tR\tcaptchaId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x04 \x01(\tR\timageData\x12\x16\n" +
	"\x06answer\x18\x05 \x01(\tR\x06answer\"I\n" +
	"\x10VerifyCaptchaReq\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x01 \x01(\tR\tcaptchaId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\"W\n" +
	"\x11VerifyCaptchaResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"o\n" +
	"\x10SendMailCodeResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x17\n" +
	"\acode_id\x18\x04 \x01(\tR\x06codeId\"\x92\x01\n" +
	"\x17SendRegisterMailCodeReq\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x01 \x01(\tR\tcaptchaId\x12!\n" +
	"\fcaptcha_code\x18\x02 \x01(\tR\vcaptchaCode\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vcode_length\x18\x04 \x01(\x05R\n" +
	"codeLength\"\xb2\x01\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"email_code\x18\x02 \x01(\tR\temailCode\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x10\n" +
	"\x03sex\x18\x06 \x01(\x05R\x03sex\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\"\x98\x01\n" +
	"\fRegisterResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12+\n" +
	"\tuser_info\x18\x05 \x01(\v2\x0e.user.UserInfoR\buserInfo\"\xbd\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x10\n" +
	"\x03sex\x18\x06 \x01(\x05R\x03sex\x12\x16\n" +
	"\x06points\x18\a \x01(\x05R\x06points\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\tR\n" +
	"createTime\"p\n" +
	"\rCaptchaConfig\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x12\x19\n" +
	"\bbg_color\x18\x04 \x01(\tR\abgColor\"\xde\x01\n" +
	"\vDrawOptions\x12&\n" +
	"\x0fuse_custom_draw\x18\x01 \x01(\bR\ruseCustomDraw\x12\x1b\n" +
	"\tdraw_text\x18\x02 \x01(\bR\bdrawText\x12\x1f\n" +
	"\vdraw_hollow\x18\x03 \x01(\bR\n" +
	"drawHollow\x12\x1b\n" +
	"\tdraw_sine\x18\x04 \x01(\bR\bdrawSine\x12$\n" +
	"\x0edraw_slim_line\x18\x05 \x01(\x05R\fdrawSlimLine\x12&\n" +
	"\x0fdraw_noise_text\x18\x06 \x01(\tR\rdrawNoiseText\"n\n" +
	"\x16UploadPreviewAvatarReq\x12\x1b\n" +
	"\tfile_data\x18\x01 \x01(\fR\bfileData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\"\x89\x01\n" +
	"\x17UploadPreviewAvatarResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vpreview_key\x18\x03 \x01(\tR\n" +
	"previewKey\x12\x1f\n" +
	"\vpreview_url\x18\x04 \x01(\tR\n" +
	"previewUrl2\xe6\x02\n" +
	"\x04User\x12F\n" +
	"\x0fGenerateCaptcha\x12\x18.user.GenerateCaptchaReq\x1a\x19.user.GenerateCaptchaResp\x12@\n" +
	"\rVerifyCaptcha\x12\x16.user.VerifyCaptchaReq\x1a\x17.user.VerifyCaptchaResp\x12M\n" +
	"\x14SendRegisterMailCode\x12\x1d.user.SendRegisterMailCodeReq\x1a\x16.user.SendMailCodeResp\x121\n" +
	"\bRegister\x12\x11.user.RegisterReq\x1a\x12.user.RegisterResp\x12R\n" +
	"\x13UploadPreviewAvatar\x12\x1c.user.UploadPreviewAvatarReq\x1a\x1d.user.UploadPreviewAvatarRespB\bZ\x06./userb\x06proto3"

var (
	file_rpc_user_proto_rawDescOnce sync.Once
	file_rpc_user_proto_rawDescData []byte
)

func file_rpc_user_proto_rawDescGZIP() []byte {
	file_rpc_user_proto_rawDescOnce.Do(func() {
		file_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_user_proto_rawDesc), len(file_rpc_user_proto_rawDesc)))
	})
	return file_rpc_user_proto_rawDescData
}

var file_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rpc_user_proto_goTypes = []any{
	(*GenerateCaptchaReq)(nil),      // 0: user.GenerateCaptchaReq
	(*GenerateCaptchaResp)(nil),     // 1: user.GenerateCaptchaResp
	(*VerifyCaptchaReq)(nil),        // 2: user.VerifyCaptchaReq
	(*VerifyCaptchaResp)(nil),       // 3: user.VerifyCaptchaResp
	(*SendMailCodeResp)(nil),        // 4: user.SendMailCodeResp
	(*SendRegisterMailCodeReq)(nil), // 5: user.SendRegisterMailCodeReq
	(*RegisterReq)(nil),             // 6: user.RegisterReq
	(*RegisterResp)(nil),            // 7: user.RegisterResp
	(*UserInfo)(nil),                // 8: user.UserInfo
	(*CaptchaConfig)(nil),           // 9: user.CaptchaConfig
	(*DrawOptions)(nil),             // 10: user.DrawOptions
	(*UploadPreviewAvatarReq)(nil),  // 11: user.UploadPreviewAvatarReq
	(*UploadPreviewAvatarResp)(nil), // 12: user.UploadPreviewAvatarResp
}
var file_rpc_user_proto_depIdxs = []int32{
	9,  // 0: user.GenerateCaptchaReq.config:type_name -> user.CaptchaConfig
	10, // 1: user.GenerateCaptchaReq.draw_opts:type_name -> user.DrawOptions
	8,  // 2: user.RegisterResp.user_info:type_name -> user.UserInfo
	0,  // 3: user.User.GenerateCaptcha:input_type -> user.GenerateCaptchaReq
	2,  // 4: user.User.VerifyCaptcha:input_type -> user.VerifyCaptchaReq
	5,  // 5: user.User.SendRegisterMailCode:input_type -> user.SendRegisterMailCodeReq
	6,  // 6: user.User.Register:input_type -> user.RegisterReq
	11, // 7: user.User.UploadPreviewAvatar:input_type -> user.UploadPreviewAvatarReq
	1,  // 8: user.User.GenerateCaptcha:output_type -> user.GenerateCaptchaResp
	3,  // 9: user.User.VerifyCaptcha:output_type -> user.VerifyCaptchaResp
	4,  // 10: user.User.SendRegisterMailCode:output_type -> user.SendMailCodeResp
	7,  // 11: user.User.Register:output_type -> user.RegisterResp
	12, // 12: user.User.UploadPreviewAvatar:output_type -> user.UploadPreviewAvatarResp
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_user_proto_init() }
func file_rpc_user_proto_init() {
	if File_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_user_proto_rawDesc), len(file_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_user_proto_goTypes,
		DependencyIndexes: file_rpc_user_proto_depIdxs,
		MessageInfos:      file_rpc_user_proto_msgTypes,
	}.Build()
	File_rpc_user_proto = out.File
	file_rpc_user_proto_goTypes = nil
	file_rpc_user_proto_depIdxs = nil
}
