// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: rpc/food.proto

package food

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Food_GetFood_FullMethodName            = "/food.Food/GetFood"
	Food_GetMyFoodList_FullMethodName      = "/food.Food/GetMyFoodList"
	Food_CreateOrUpdateFood_FullMethodName = "/food.Food/CreateOrUpdateFood"
)

// FoodClient is the client API for Food service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 美食服务
type FoodClient interface {
	// 查询单个美食基础信息
	GetFood(ctx context.Context, in *GetFoodReq, opts ...grpc.CallOption) (*GetFoodResp, error)
	// 查询我的美食列表
	GetMyFoodList(ctx context.Context, in *GetMyFoodListReq, opts ...grpc.CallOption) (*GetMyFoodListResp, error)
	// 新增/修改美食信息
	CreateOrUpdateFood(ctx context.Context, in *CreateOrUpdateFoodReq, opts ...grpc.CallOption) (*CreateOrUpdateFoodResp, error)
}

type foodClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodClient(cc grpc.ClientConnInterface) FoodClient {
	return &foodClient{cc}
}

func (c *foodClient) GetFood(ctx context.Context, in *GetFoodReq, opts ...grpc.CallOption) (*GetFoodResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFoodResp)
	err := c.cc.Invoke(ctx, Food_GetFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodClient) GetMyFoodList(ctx context.Context, in *GetMyFoodListReq, opts ...grpc.CallOption) (*GetMyFoodListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyFoodListResp)
	err := c.cc.Invoke(ctx, Food_GetMyFoodList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodClient) CreateOrUpdateFood(ctx context.Context, in *CreateOrUpdateFoodReq, opts ...grpc.CallOption) (*CreateOrUpdateFoodResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateFoodResp)
	err := c.cc.Invoke(ctx, Food_CreateOrUpdateFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodServer is the server API for Food service.
// All implementations must embed UnimplementedFoodServer
// for forward compatibility.
//
// 美食服务
type FoodServer interface {
	// 查询单个美食基础信息
	GetFood(context.Context, *GetFoodReq) (*GetFoodResp, error)
	// 查询我的美食列表
	GetMyFoodList(context.Context, *GetMyFoodListReq) (*GetMyFoodListResp, error)
	// 新增/修改美食信息
	CreateOrUpdateFood(context.Context, *CreateOrUpdateFoodReq) (*CreateOrUpdateFoodResp, error)
	mustEmbedUnimplementedFoodServer()
}

// UnimplementedFoodServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFoodServer struct{}

func (UnimplementedFoodServer) GetFood(context.Context, *GetFoodReq) (*GetFoodResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFood not implemented")
}
func (UnimplementedFoodServer) GetMyFoodList(context.Context, *GetMyFoodListReq) (*GetMyFoodListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyFoodList not implemented")
}
func (UnimplementedFoodServer) CreateOrUpdateFood(context.Context, *CreateOrUpdateFoodReq) (*CreateOrUpdateFoodResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateFood not implemented")
}
func (UnimplementedFoodServer) mustEmbedUnimplementedFoodServer() {}
func (UnimplementedFoodServer) testEmbeddedByValue()              {}

// UnsafeFoodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FoodServer will
// result in compilation errors.
type UnsafeFoodServer interface {
	mustEmbedUnimplementedFoodServer()
}

func RegisterFoodServer(s grpc.ServiceRegistrar, srv FoodServer) {
	// If the following call panics, it indicates UnimplementedFoodServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Food_ServiceDesc, srv)
}

func _Food_GetFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFoodReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServer).GetFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Food_GetFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServer).GetFood(ctx, req.(*GetFoodReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Food_GetMyFoodList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyFoodListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServer).GetMyFoodList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Food_GetMyFoodList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServer).GetMyFoodList(ctx, req.(*GetMyFoodListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Food_CreateOrUpdateFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateFoodReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServer).CreateOrUpdateFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Food_CreateOrUpdateFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServer).CreateOrUpdateFood(ctx, req.(*CreateOrUpdateFoodReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Food_ServiceDesc is the grpc.ServiceDesc for Food service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Food_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "food.Food",
	HandlerType: (*FoodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFood",
			Handler:    _Food_GetFood_Handler,
		},
		{
			MethodName: "GetMyFoodList",
			Handler:    _Food_GetMyFoodList_Handler,
		},
		{
			MethodName: "CreateOrUpdateFood",
			Handler:    _Food_CreateOrUpdateFood_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/food.proto",
}
