// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: rpc/food.proto

package food

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 美食步骤详情
type FoodStepDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          string                 `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`                                  // 步骤名称，如 "步骤1"
	StepImgUrl    string                 `protobuf:"bytes,2,opt,name=step_img_url,json=stepImgUrl,proto3" json:"step_img_url,omitempty"`  // 步骤图片URL（对应 JSON 中的 stepImgUrl 或 img）
	StepContent   string                 `protobuf:"bytes,3,opt,name=step_content,json=stepContent,proto3" json:"step_content,omitempty"` // 步骤内容（对应 JSON 中的 stepContent 或 content）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodStepDetail) Reset() {
	*x = FoodStepDetail{}
	mi := &file_rpc_food_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodStepDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodStepDetail) ProtoMessage() {}

func (x *FoodStepDetail) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_food_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodStepDetail.ProtoReflect.Descriptor instead.
func (*FoodStepDetail) Descriptor() ([]byte, []int) {
	return file_rpc_food_proto_rawDescGZIP(), []int{0}
}

func (x *FoodStepDetail) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *FoodStepDetail) GetStepImgUrl() string {
	if x != nil {
		return x.StepImgUrl
	}
	return ""
}

func (x *FoodStepDetail) GetStepContent() string {
	if x != nil {
		return x.StepContent
	}
	return ""
}

// 美食清单项
type FoodListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipesTag    string                 `protobuf:"bytes,1,opt,name=recipes_tag,json=recipesTag,proto3" json:"recipes_tag,omitempty"`       // 食材分类，如 "菜"、"肉"、"调味品"
	RecipesName   string                 `protobuf:"bytes,2,opt,name=recipes_name,json=recipesName,proto3" json:"recipes_name,omitempty"`    // 食材名称
	RecipesSpecs  string                 `protobuf:"bytes,3,opt,name=recipes_specs,json=recipesSpecs,proto3" json:"recipes_specs,omitempty"` // 食材规格/数量，如 "1500g"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodListItem) Reset() {
	*x = FoodListItem{}
	mi := &file_rpc_food_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodListItem) ProtoMessage() {}

func (x *FoodListItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_food_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodListItem.ProtoReflect.Descriptor instead.
func (*FoodListItem) Descriptor() ([]byte, []int) {
	return file_rpc_food_proto_rawDescGZIP(), []int{1}
}

func (x *FoodListItem) GetRecipesTag() string {
	if x != nil {
		return x.RecipesTag
	}
	return ""
}

func (x *FoodListItem) GetRecipesName() string {
	if x != nil {
		return x.RecipesName
	}
	return ""
}

func (x *FoodListItem) GetRecipesSpecs() string {
	if x != nil {
		return x.RecipesSpecs
	}
	return ""
}

// 美食信息
type FoodInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FoodName       string                 `protobuf:"bytes,3,opt,name=food_name,json=foodName,proto3" json:"food_name,omitempty"`
	FoodDes        string                 `protobuf:"bytes,4,opt,name=food_des,json=foodDes,proto3" json:"food_des,omitempty"`
	FoodCateTag    int32                  `protobuf:"varint,5,opt,name=food_cate_tag,json=foodCateTag,proto3" json:"food_cate_tag,omitempty"`
	FoodUrl        string                 `protobuf:"bytes,6,opt,name=food_url,json=foodUrl,proto3" json:"food_url,omitempty"`
	FoodVideoUrl   string                 `protobuf:"bytes,7,opt,name=food_video_url,json=foodVideoUrl,proto3" json:"food_video_url,omitempty"`
	FoodTime       int32                  `protobuf:"varint,8,opt,name=food_time,json=foodTime,proto3" json:"food_time,omitempty"`
	FoodDifficulty int32                  `protobuf:"varint,9,opt,name=food_difficulty,json=foodDifficulty,proto3" json:"food_difficulty,omitempty"`
	FoodDetail     []*FoodStepDetail      `protobuf:"bytes,10,rep,name=food_detail,json=foodDetail,proto3" json:"food_detail,omitempty"` // 美食制作详情（结构化数据）
	FoodList       []*FoodListItem        `protobuf:"bytes,11,rep,name=food_list,json=foodList,proto3" json:"food_list,omitempty"`       // 美食清单（结构化数据）
	FoodStatus     int32                  `protobuf:"varint,12,opt,name=food_status,json=foodStatus,proto3" json:"food_status,omitempty"`
	SkuIds         []int64                `protobuf:"varint,13,rep,packed,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"` // 美食关联的商品ids（结构化数据）
	FoodCreatetime string                 `protobuf:"bytes,14,opt,name=food_createtime,json=foodCreatetime,proto3" json:"food_createtime,omitempty"`
	FoodUpdatetime string                 `protobuf:"bytes,15,opt,name=food_updatetime,json=foodUpdatetime,proto3" json:"food_updatetime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FoodInfo) Reset() {
	*x = FoodInfo{}
	mi := &file_rpc_food_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodInfo) ProtoMessage() {}

func (x *FoodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_food_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodInfo.ProtoReflect.Descriptor instead.
func (*FoodInfo) Descriptor() ([]byte, []int) {
	return file_rpc_food_proto_rawDescGZIP(), []int{2}
}

func (x *FoodInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FoodInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FoodInfo) GetFoodName() string {
	if x != nil {
		return x.FoodName
	}
	return ""
}

func (x *FoodInfo) GetFoodDes() string {
	if x != nil {
		return x.FoodDes
	}
	return ""
}

func (x *FoodInfo) GetFoodCateTag() int32 {
	if x != nil {
		return x.FoodCateTag
	}
	return 0
}

func (x *FoodInfo) GetFoodUrl() string {
	if x != nil {
		return x.FoodUrl
	}
	return ""
}

func (x *FoodInfo) GetFoodVideoUrl() string {
	if x != nil {
		return x.FoodVideoUrl
	}
	return ""
}

func (x *FoodInfo) GetFoodTime() int32 {
	if x != nil {
		return x.FoodTime
	}
	return 0
}

func (x *FoodInfo) GetFoodDifficulty() int32 {
	if x != nil {
		return x.FoodDifficulty
	}
	return 0
}

func (x *FoodInfo) GetFoodDetail() []*FoodStepDetail {
	if x != nil {
		return x.FoodDetail
	}
	return nil
}

func (x *FoodInfo) GetFoodList() []*FoodListItem {
	if x != nil {
		return x.FoodList
	}
	return nil
}

func (x *FoodInfo) GetFoodStatus() int32 {
	if x != nil {
		return x.FoodStatus
	}
	return 0
}

func (x *FoodInfo) GetSkuIds() []int64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

func (x *FoodInfo) GetFoodCreatetime() string {
	if x != nil {
		return x.FoodCreatetime
	}
	return ""
}

func (x *FoodInfo) GetFoodUpdatetime() string {
	if x != nil {
		return x.FoodUpdatetime
	}
	return ""
}

// 获取美食详情
type GetFoodReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodId        int64                  `protobuf:"varint,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoodReq) Reset() {
	*x = GetFoodReq{}
	mi := &file_rpc_food_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoodReq) ProtoMessage() {}

func (x *GetFoodReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_food_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoodReq.ProtoReflect.Descriptor instead.
func (*GetFoodReq) Descriptor() ([]byte, []int) {
	return file_rpc_food_proto_rawDescGZIP(), []int{3}
}

func (x *GetFoodReq) GetFoodId() int64 {
	if x != nil {
		return x.FoodId
	}
	return 0
}

type GetFoodResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FoodInfo      *FoodInfo              `protobuf:"bytes,3,opt,name=food_info,json=foodInfo,proto3" json:"food_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFoodResp) Reset() {
	*x = GetFoodResp{}
	mi := &file_rpc_food_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFoodResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoodResp) ProtoMessage() {}

func (x *GetFoodResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_food_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoodResp.ProtoReflect.Descriptor instead.
func (*GetFoodResp) Descriptor() ([]byte, []int) {
	return file_rpc_food_proto_rawDescGZIP(), []int{4}
}

func (x *GetFoodResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetFoodResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFoodResp) GetFoodInfo() *FoodInfo {
	if x != nil {
		return x.FoodInfo
	}
	return nil
}

// 查询我的美食列表
type GetMyFoodListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyFoodListReq) Reset() {
	*x = GetMyFoodListReq{}
	mi := &file_rpc_food_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyFoodListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyFoodListReq) ProtoMessage() {}

func (x *GetMyFoodListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_food_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyFoodListReq.ProtoReflect.Descriptor instead.
func (*GetMyFoodListReq) Descriptor() ([]byte, []int) {
	return file_rpc_food_proto_rawDescGZIP(), []int{5}
}

func (x *GetMyFoodListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetMyFoodListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMyFoodListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetMyFoodListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FoodList      []*FoodInfo            `protobuf:"bytes,6,rep,name=food_list,json=foodList,proto3" json:"food_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyFoodListResp) Reset() {
	*x = GetMyFoodListResp{}
	mi := &file_rpc_food_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyFoodListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyFoodListResp) ProtoMessage() {}

func (x *GetMyFoodListResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_food_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyFoodListResp.ProtoReflect.Descriptor instead.
func (*GetMyFoodListResp) Descriptor() ([]byte, []int) {
	return file_rpc_food_proto_rawDescGZIP(), []int{6}
}

func (x *GetMyFoodListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMyFoodListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMyFoodListResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetMyFoodListResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMyFoodListResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetMyFoodListResp) GetFoodList() []*FoodInfo {
	if x != nil {
		return x.FoodList
	}
	return nil
}

// 新增/修改美食信息
type CreateOrUpdateFoodReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FoodId         int64                  `protobuf:"varint,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"` // 如果为0或未提供，则为新增；否则为修改
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FoodName       string                 `protobuf:"bytes,3,opt,name=food_name,json=foodName,proto3" json:"food_name,omitempty"`
	FoodDes        string                 `protobuf:"bytes,4,opt,name=food_des,json=foodDes,proto3" json:"food_des,omitempty"`
	FoodCateTag    int32                  `protobuf:"varint,5,opt,name=food_cate_tag,json=foodCateTag,proto3" json:"food_cate_tag,omitempty"`
	FoodUrl        string                 `protobuf:"bytes,6,opt,name=food_url,json=foodUrl,proto3" json:"food_url,omitempty"`
	FoodVideoUrl   string                 `protobuf:"bytes,7,opt,name=food_video_url,json=foodVideoUrl,proto3" json:"food_video_url,omitempty"`
	FoodTime       int32                  `protobuf:"varint,8,opt,name=food_time,json=foodTime,proto3" json:"food_time,omitempty"`
	FoodDifficulty int32                  `protobuf:"varint,9,opt,name=food_difficulty,json=foodDifficulty,proto3" json:"food_difficulty,omitempty"`
	FoodDetail     []*FoodStepDetail      `protobuf:"bytes,10,rep,name=food_detail,json=foodDetail,proto3" json:"food_detail,omitempty"` // 美食制作详情（结构化数据）
	FoodList       []*FoodListItem        `protobuf:"bytes,11,rep,name=food_list,json=foodList,proto3" json:"food_list,omitempty"`       // 美食清单（结构化数据）
	SkuIds         []int64                `protobuf:"varint,12,rep,packed,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`     // 美食关联的商品ids（结构化数据，可选）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrUpdateFoodReq) Reset() {
	*x = CreateOrUpdateFoodReq{}
	mi := &file_rpc_food_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateFoodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateFoodReq) ProtoMessage() {}

func (x *CreateOrUpdateFoodReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_food_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateFoodReq.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateFoodReq) Descriptor() ([]byte, []int) {
	return file_rpc_food_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOrUpdateFoodReq) GetFoodId() int64 {
	if x != nil {
		return x.FoodId
	}
	return 0
}

func (x *CreateOrUpdateFoodReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrUpdateFoodReq) GetFoodName() string {
	if x != nil {
		return x.FoodName
	}
	return ""
}

func (x *CreateOrUpdateFoodReq) GetFoodDes() string {
	if x != nil {
		return x.FoodDes
	}
	return ""
}

func (x *CreateOrUpdateFoodReq) GetFoodCateTag() int32 {
	if x != nil {
		return x.FoodCateTag
	}
	return 0
}

func (x *CreateOrUpdateFoodReq) GetFoodUrl() string {
	if x != nil {
		return x.FoodUrl
	}
	return ""
}

func (x *CreateOrUpdateFoodReq) GetFoodVideoUrl() string {
	if x != nil {
		return x.FoodVideoUrl
	}
	return ""
}

func (x *CreateOrUpdateFoodReq) GetFoodTime() int32 {
	if x != nil {
		return x.FoodTime
	}
	return 0
}

func (x *CreateOrUpdateFoodReq) GetFoodDifficulty() int32 {
	if x != nil {
		return x.FoodDifficulty
	}
	return 0
}

func (x *CreateOrUpdateFoodReq) GetFoodDetail() []*FoodStepDetail {
	if x != nil {
		return x.FoodDetail
	}
	return nil
}

func (x *CreateOrUpdateFoodReq) GetFoodList() []*FoodListItem {
	if x != nil {
		return x.FoodList
	}
	return nil
}

func (x *CreateOrUpdateFoodReq) GetSkuIds() []int64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type CreateOrUpdateFoodResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FoodId        int64                  `protobuf:"varint,3,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`      // 新增或修改的美食ID
	FoodInfo      *FoodInfo              `protobuf:"bytes,4,opt,name=food_info,json=foodInfo,proto3" json:"food_info,omitempty"` // 美食信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateFoodResp) Reset() {
	*x = CreateOrUpdateFoodResp{}
	mi := &file_rpc_food_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateFoodResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateFoodResp) ProtoMessage() {}

func (x *CreateOrUpdateFoodResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_food_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateFoodResp.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateFoodResp) Descriptor() ([]byte, []int) {
	return file_rpc_food_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOrUpdateFoodResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateOrUpdateFoodResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateOrUpdateFoodResp) GetFoodId() int64 {
	if x != nil {
		return x.FoodId
	}
	return 0
}

func (x *CreateOrUpdateFoodResp) GetFoodInfo() *FoodInfo {
	if x != nil {
		return x.FoodInfo
	}
	return nil
}

var File_rpc_food_proto protoreflect.FileDescriptor

const file_rpc_food_proto_rawDesc = "" +
	"\n" +
	"\x0erpc/food.proto\x12\x04food\"i\n" +
	"\x0eFoodStepDetail\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12 \n" +
	"\fstep_img_url\x18\x02 \x01(\tR\n" +
	"stepImgUrl\x12!\n" +
	"\fstep_content\x18\x03 \x01(\tR\vstepContent\"w\n" +
	"\fFoodListItem\x12\x1f\n" +
	"\vrecipes_tag\x18\x01 \x01(\tR\n" +
	"recipesTag\x12!\n" +
	"\frecipes_name\x18\x02 \x01(\tR\vrecipesName\x12#\n" +
	"\rrecipes_specs\x18\x03 \x01(\tR\frecipesSpecs\"\x8a\x04\n" +
	"\bFoodInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfood_name\x18\x03 \x01(\tR\bfoodName\x12\x19\n" +
	"\bfood_des\x18\x04 \x01(\tR\afoodDes\x12\"\n" +
	"\rfood_cate_tag\x18\x05 \x01(\x05R\vfoodCateTag\x12\x19\n" +
	"\bfood_url\x18\x06 \x01(\tR\afoodUrl\x12$\n" +
	"\x0efood_video_url\x18\a \x01(\tR\ffoodVideoUrl\x12\x1b\n" +
	"\tfood_time\x18\b \x01(\x05R\bfoodTime\x12'\n" +
	"\x0ffood_difficulty\x18\t \x01(\x05R\x0efoodDifficulty\x125\n" +
	"\vfood_detail\x18\n" +
	" \x03(\v2\x14.food.FoodStepDetailR\n" +
	"foodDetail\x12/\n" +
	"\tfood_list\x18\v \x03(\v2\x12.food.FoodListItemR\bfoodList\x12\x1f\n" +
	"\vfood_status\x18\f \x01(\x05R\n" +
	"foodStatus\x12\x17\n" +
	"\asku_ids\x18\r \x03(\x03R\x06skuIds\x12'\n" +
	"\x0ffood_createtime\x18\x0e \x01(\tR\x0efoodCreatetime\x12'\n" +
	"\x0ffood_updatetime\x18\x0f \x01(\tR\x0efoodUpdatetime\"%\n" +
	"\n" +
	"GetFoodReq\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\x03R\x06foodId\"h\n" +
	"\vGetFoodResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\tfood_info\x18\x03 \x01(\v2\x0e.food.FoodInfoR\bfoodInfo\"\\\n" +
	"\x10GetMyFoodListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xb5\x01\n" +
	"\x11GetMyFoodListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12+\n" +
	"\tfood_list\x18\x06 \x03(\v2\x0e.food.FoodInfoR\bfoodList\"\xad\x03\n" +
	"\x15CreateOrUpdateFoodReq\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\x03R\x06foodId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfood_name\x18\x03 \x01(\tR\bfoodName\x12\x19\n" +
	"\bfood_des\x18\x04 \x01(\tR\afoodDes\x12\"\n" +
	"\rfood_cate_tag\x18\x05 \x01(\x05R\vfoodCateTag\x12\x19\n" +
	"\bfood_url\x18\x06 \x01(\tR\afoodUrl\x12$\n" +
	"\x0efood_video_url\x18\a \x01(\tR\ffoodVideoUrl\x12\x1b\n" +
	"\tfood_time\x18\b \x01(\x05R\bfoodTime\x12'\n" +
	"\x0ffood_difficulty\x18\t \x01(\x05R\x0efoodDifficulty\x125\n" +
	"\vfood_detail\x18\n" +
	" \x03(\v2\x14.food.FoodStepDetailR\n" +
	"foodDetail\x12/\n" +
	"\tfood_list\x18\v \x03(\v2\x12.food.FoodListItemR\bfoodList\x12\x17\n" +
	"\asku_ids\x18\f \x03(\x03R\x06skuIds\"\x8c\x01\n" +
	"\x16CreateOrUpdateFoodResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\afood_id\x18\x03 \x01(\x03R\x06foodId\x12+\n" +
	"\tfood_info\x18\x04 \x01(\v2\x0e.food.FoodInfoR\bfoodInfo2\xc9\x01\n" +
	"\x04Food\x12.\n" +
	"\aGetFood\x12\x10.food.GetFoodReq\x1a\x11.food.GetFoodResp\x12@\n" +
	"\rGetMyFoodList\x12\x16.food.GetMyFoodListReq\x1a\x17.food.GetMyFoodListResp\x12O\n" +
	"\x12CreateOrUpdateFood\x12\x1b.food.CreateOrUpdateFoodReq\x1a\x1c.food.CreateOrUpdateFoodRespB\bZ\x06./foodb\x06proto3"

var (
	file_rpc_food_proto_rawDescOnce sync.Once
	file_rpc_food_proto_rawDescData []byte
)

func file_rpc_food_proto_rawDescGZIP() []byte {
	file_rpc_food_proto_rawDescOnce.Do(func() {
		file_rpc_food_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_food_proto_rawDesc), len(file_rpc_food_proto_rawDesc)))
	})
	return file_rpc_food_proto_rawDescData
}

var file_rpc_food_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rpc_food_proto_goTypes = []any{
	(*FoodStepDetail)(nil),         // 0: food.FoodStepDetail
	(*FoodListItem)(nil),           // 1: food.FoodListItem
	(*FoodInfo)(nil),               // 2: food.FoodInfo
	(*GetFoodReq)(nil),             // 3: food.GetFoodReq
	(*GetFoodResp)(nil),            // 4: food.GetFoodResp
	(*GetMyFoodListReq)(nil),       // 5: food.GetMyFoodListReq
	(*GetMyFoodListResp)(nil),      // 6: food.GetMyFoodListResp
	(*CreateOrUpdateFoodReq)(nil),  // 7: food.CreateOrUpdateFoodReq
	(*CreateOrUpdateFoodResp)(nil), // 8: food.CreateOrUpdateFoodResp
}
var file_rpc_food_proto_depIdxs = []int32{
	0,  // 0: food.FoodInfo.food_detail:type_name -> food.FoodStepDetail
	1,  // 1: food.FoodInfo.food_list:type_name -> food.FoodListItem
	2,  // 2: food.GetFoodResp.food_info:type_name -> food.FoodInfo
	2,  // 3: food.GetMyFoodListResp.food_list:type_name -> food.FoodInfo
	0,  // 4: food.CreateOrUpdateFoodReq.food_detail:type_name -> food.FoodStepDetail
	1,  // 5: food.CreateOrUpdateFoodReq.food_list:type_name -> food.FoodListItem
	2,  // 6: food.CreateOrUpdateFoodResp.food_info:type_name -> food.FoodInfo
	3,  // 7: food.Food.GetFood:input_type -> food.GetFoodReq
	5,  // 8: food.Food.GetMyFoodList:input_type -> food.GetMyFoodListReq
	7,  // 9: food.Food.CreateOrUpdateFood:input_type -> food.CreateOrUpdateFoodReq
	4,  // 10: food.Food.GetFood:output_type -> food.GetFoodResp
	6,  // 11: food.Food.GetMyFoodList:output_type -> food.GetMyFoodListResp
	8,  // 12: food.Food.CreateOrUpdateFood:output_type -> food.CreateOrUpdateFoodResp
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_rpc_food_proto_init() }
func file_rpc_food_proto_init() {
	if File_rpc_food_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_food_proto_rawDesc), len(file_rpc_food_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_food_proto_goTypes,
		DependencyIndexes: file_rpc_food_proto_depIdxs,
		MessageInfos:      file_rpc_food_proto_msgTypes,
	}.Build()
	File_rpc_food_proto = out.File
	file_rpc_food_proto_goTypes = nil
	file_rpc_food_proto_depIdxs = nil
}
