// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAddressFieldNames          = builder.RawFieldNames(&UserAddress{})
	userAddressRows                = strings.Join(userAddressFieldNames, ",")
	userAddressRowsExpectAutoSet   = strings.Join(stringx.Remove(userAddressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAddressRowsWithPlaceHolder = strings.Join(stringx.Remove(userAddressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserAddressIdPrefix = "cache:userAddress:id:"
)

type (
	userAddressModel interface {
		Insert(ctx context.Context, data *UserAddress) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAddress, error)
		Update(ctx context.Context, data *UserAddress) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserAddressModel struct {
		sqlc.CachedConn
		table string
	}

	UserAddress struct {
		Id            uint64         `db:"id"`
		UserId        sql.NullInt64  `db:"user_id"`        // 用户id
		DefaultStatus sql.NullInt64  `db:"default_status"` // 是否默认收货地址：0否 1是
		ReceiveName   sql.NullString `db:"receive_name"`   // 收发货人姓名
		Phone         sql.NullString `db:"phone"`          // 收货人电话
		Province      sql.NullString `db:"province"`       // 省/直辖市
		City          sql.NullString `db:"city"`           // 市
		Region        sql.NullString `db:"region"`         // 区
		DetailAddress sql.NullString `db:"detail_address"` // 详细地址
		CreateTime    sql.NullTime   `db:"create_time"`    // 创建时间
		UpdateTime    sql.NullTime   `db:"update_time"`    // 更新时间
	}
)

func newUserAddressModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserAddressModel {
	return &defaultUserAddressModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_address`",
	}
}

func (m *defaultUserAddressModel) Delete(ctx context.Context, id uint64) error {
	userAddressIdKey := fmt.Sprintf("%s%v", cacheUserAddressIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userAddressIdKey)
	return err
}

func (m *defaultUserAddressModel) FindOne(ctx context.Context, id uint64) (*UserAddress, error) {
	userAddressIdKey := fmt.Sprintf("%s%v", cacheUserAddressIdPrefix, id)
	var resp UserAddress
	err := m.QueryRowCtx(ctx, &resp, userAddressIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAddressRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAddressModel) Insert(ctx context.Context, data *UserAddress) (sql.Result, error) {
	userAddressIdKey := fmt.Sprintf("%s%v", cacheUserAddressIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, userAddressRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.DefaultStatus, data.ReceiveName, data.Phone, data.Province, data.City, data.Region, data.DetailAddress)
	}, userAddressIdKey)
	return ret, err
}

func (m *defaultUserAddressModel) Update(ctx context.Context, data *UserAddress) error {
	userAddressIdKey := fmt.Sprintf("%s%v", cacheUserAddressIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAddressRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.DefaultStatus, data.ReceiveName, data.Phone, data.Province, data.City, data.Region, data.DetailAddress, data.Id)
	}, userAddressIdKey)
	return err
}

func (m *defaultUserAddressModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserAddressIdPrefix, primary)
}

func (m *defaultUserAddressModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAddressRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserAddressModel) tableName() string {
	return m.table
}
