// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type GenerateFeedCacheRequest struct {
	Operator string `json:"operator,optional"` // 触发人或自动化标识
	Force    bool   `json:"force,optional"`    // true 时强制刷新
}

type GenerateFeedCacheResponse struct {
	Code        int           `json:"code"`
	Message     string        `json:"message"`
	FeedVersion string        `json:"feed_version"` // 当前版本号（时间戳）
	RecipesList []RecipesInfo `json:"recipes_list"`
}

type HomeFeedRequest struct {
	UserId     int64  `form:"user_id,optional"`
	DeviceId   string `form:"device_id,optional"`
	Version    string `form:"version,optional"` // 指定的 feed 版本，缺省时使用最新
	PageSize   int64  `form:"page_size,optional,default=10"`
	Cursor     string `form:"cursor,optional"`
	NeedDetail bool   `form:"need_detail,optional,default=true"` // true 返回详细食谱信息
}

type HomeFeedResponse struct {
	Code        int           `json:"code"`
	Message     string        `json:"message"`
	FeedVersion string        `json:"feed_version"`
	RecipesList []RecipesInfo `json:"recipes_list,optional"`
	Cursor      string        `json:"cursor,optional"`
	HasMore     bool          `json:"has_more"`
}

type RecipesInfo struct {
	Id                 int64  `json:"id"` // 食谱ID
	RecipesName        string `json:"recipes_name"`
	RecipesUrl         string `json:"recipes_url"`
	RecipesUserName    string `json:"recipes_user_name"`
	RecipesUserAvatar  string `json:"recipes_user_avatar"`
	RecipesDescription string `json:"recipes_description"`
}
