// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type GenerateFeedCacheRequest struct {
	Operator string `json:"operator,optional"` // 触发人或自动化标识
	Force    bool   `json:"force,optional"`    // true 时强制刷新
}

type GenerateFeedCacheResponse struct {
	Code        int           `json:"code"`
	Message     string        `json:"message"`
	FeedVersion string        `json:"feed_version"` // 当前版本号（时间戳）
	RecipesList []RecipesInfo `json:"recipes_list"`
}

type HomeFeedRequest struct {
	UserId      int64  `json:"user_id"`                       // 用户id
	FeedVersion string `json:"feed_version,optional"`         // feed 流请求版本号
	PullRefresh bool   `json:"pull_refresh,optional"`         // 是否下拉刷新
	Page        int64  `json:"page,optional"`                 // 页码
	PageSize    int64  `json:"page_size,optional,default=10"` // 每页数量
}

type HomeFeedResponse struct {
	Code        int           `json:"code"`
	Message     string        `json:"message"`
	FeedVersion string        `json:"feed_version"`
	CurrPage    int64         `json:"curr_page"`
	HasNextPage bool          `json:"has_next_page"`
	RecipesList []RecipesInfo `json:"recipes_list,optional"`
}

type RecipesInfo struct {
	Id                 int64  `json:"id"` // 食谱ID
	RecipesName        string `json:"recipes_name"`
	RecipesUrl         string `json:"recipes_url"`
	RecipesUserName    string `json:"recipes_user_name"`
	RecipesUserAvatar  string `json:"recipes_user_avatar"`
	RecipesDescription string `json:"recipes_description"`
}
