// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: user.proto

package server

import (
	"context"

	"github.com/hd2yao/ecshop/user/rpc/internal/logic"
	"github.com/hd2yao/ecshop/user/rpc/internal/svc"
	"github.com/hd2yao/ecshop/user/rpc/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 图形验证码
func (s *UserServer) GenerateCaptcha(ctx context.Context, in *user.GenerateCaptchaReq) (*user.GenerateCaptchaResp, error) {
	l := logic.NewGenerateCaptchaLogic(ctx, s.svcCtx)
	return l.GenerateCaptcha(in)
}

func (s *UserServer) VerifyCaptcha(ctx context.Context, in *user.VerifyCaptchaReq) (*user.VerifyCaptchaResp, error) {
	l := logic.NewVerifyCaptchaLogic(ctx, s.svcCtx)
	return l.VerifyCaptcha(in)
}

// 邮件验证码
func (s *UserServer) SendMailCode(ctx context.Context, in *user.SendMailCodeReq) (*user.SendMailCodeResp, error) {
	l := logic.NewSendMailCodeLogic(ctx, s.svcCtx)
	return l.SendMailCode(in)
}

func (s *UserServer) VerifyMailCode(ctx context.Context, in *user.VerifyMailCodeReq) (*user.VerifyMailCodeResp, error) {
	l := logic.NewVerifyMailCodeLogic(ctx, s.svcCtx)
	return l.VerifyMailCode(in)
}

func (s *UserServer) SendRegisterMailCode(ctx context.Context, in *user.SendRegisterMailCodeReq) (*user.SendMailCodeResp, error) {
	l := logic.NewSendRegisterMailCodeLogic(ctx, s.svcCtx)
	return l.SendRegisterMailCode(in)
}

// 用户注册
func (s *UserServer) Register(ctx context.Context, in *user.RegisterReq) (*user.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 文件上传
func (s *UserServer) UploadAvatar(ctx context.Context, in *user.UploadAvatarReq) (*user.UploadAvatarResp, error) {
	l := logic.NewUploadAvatarLogic(ctx, s.svcCtx)
	return l.UploadAvatar(in)
}
