// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: home.proto

package server

import (
	"context"

	"github.com/hd2yao/ecshop/home/rpc/internal/logic"
	"github.com/hd2yao/ecshop/home/rpc/internal/svc"
	"github.com/hd2yao/ecshop/home/rpc/types/home"
)

type HomeServer struct {
	svcCtx *svc.ServiceContext
	home.UnimplementedHomeServer
}

func NewHomeServer(svcCtx *svc.ServiceContext) *HomeServer {
	return &HomeServer{
		svcCtx: svcCtx,
	}
}

// 生成 feed 食谱缓存
func (s *HomeServer) GenerateFeedCache(ctx context.Context, in *home.GenerateFeedCacheReq) (*home.GenerateFeedCacheResp, error) {
	l := logic.NewGenerateFeedCacheLogic(ctx, s.svcCtx)
	return l.GenerateFeedCache(in)
}

// 获取首页 feed 食谱列表
func (s *HomeServer) GetHomeFeed(ctx context.Context, in *home.HomeFeedReq) (*home.HomeFeedResp, error) {
	l := logic.NewGetHomeFeedLogic(ctx, s.svcCtx)
	return l.GetHomeFeed(in)
}
