// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	feed "github.com/hd2yao/ecshop/home/api/internal/handler/feed"
	"github.com/hd2yao/ecshop/home/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 生成首页 feed 食谱缓存（写入 Redis）
				Method:  http.MethodPost,
				Path:    "/cache/generate",
				Handler: feed.GenerateFeedCacheHandler(serverCtx),
			},
			{
				// 获取首页 feed 食谱列表
				Method:  http.MethodGet,
				Path:    "/recipes",
				Handler: feed.GetHomeFeedHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/home/feed"),
	)
}
