// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: home.proto

package homeclient

import (
	"context"

	"github.com/hd2yao/ecshop/home/rpc/types/home"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GenerateFeedCacheReq  = home.GenerateFeedCacheReq
	GenerateFeedCacheResp = home.GenerateFeedCacheResp
	HomeFeedReq           = home.HomeFeedReq
	HomeFeedResp          = home.HomeFeedResp
	RecipesInfo           = home.RecipesInfo

	Home interface {
		// 生成 feed 食谱缓存
		GenerateFeedCache(ctx context.Context, in *GenerateFeedCacheReq, opts ...grpc.CallOption) (*GenerateFeedCacheResp, error)
		// 获取首页 feed 食谱列表
		GetHomeFeed(ctx context.Context, in *HomeFeedReq, opts ...grpc.CallOption) (*HomeFeedResp, error)
	}

	defaultHome struct {
		cli zrpc.Client
	}
)

func NewHome(cli zrpc.Client) Home {
	return &defaultHome{
		cli: cli,
	}
}

// 生成 feed 食谱缓存
func (m *defaultHome) GenerateFeedCache(ctx context.Context, in *GenerateFeedCacheReq, opts ...grpc.CallOption) (*GenerateFeedCacheResp, error) {
	client := home.NewHomeClient(m.cli.Conn())
	return client.GenerateFeedCache(ctx, in, opts...)
}

// 获取首页 feed 食谱列表
func (m *defaultHome) GetHomeFeed(ctx context.Context, in *HomeFeedReq, opts ...grpc.CallOption) (*HomeFeedResp, error) {
	client := home.NewHomeClient(m.cli.Conn())
	return client.GetHomeFeed(ctx, in, opts...)
}
