// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAttentionFieldNames          = builder.RawFieldNames(&UserAttention{})
	userAttentionRows                = strings.Join(userAttentionFieldNames, ",")
	userAttentionRowsExpectAutoSet   = strings.Join(stringx.Remove(userAttentionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAttentionRowsWithPlaceHolder = strings.Join(stringx.Remove(userAttentionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserAttentionIdPrefix = "cache:userAttention:id:"
)

type (
	userAttentionModel interface {
		Insert(ctx context.Context, data *UserAttention) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserAttention, error)
		Update(ctx context.Context, data *UserAttention) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserAttentionModel struct {
		sqlc.CachedConn
		table string
	}

	UserAttention struct {
		Id          int64     `db:"id"`           // 主键id
		UserId      int64     `db:"user_id"`      // 当前博主用户id
		AttentionId int64     `db:"attention_id"` // 关注博主用户id
		CreateTime  time.Time `db:"create_time"`  // 创建设计，会按这个字段排序
		IsDel       int64     `db:"is_del"`       // 是否删除，0 正常 1 删除
	}
)

func newUserAttentionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserAttentionModel {
	return &defaultUserAttentionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_attention`",
	}
}

func (m *defaultUserAttentionModel) Delete(ctx context.Context, id int64) error {
	userAttentionIdKey := fmt.Sprintf("%s%v", cacheUserAttentionIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userAttentionIdKey)
	return err
}

func (m *defaultUserAttentionModel) FindOne(ctx context.Context, id int64) (*UserAttention, error) {
	userAttentionIdKey := fmt.Sprintf("%s%v", cacheUserAttentionIdPrefix, id)
	var resp UserAttention
	err := m.QueryRowCtx(ctx, &resp, userAttentionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAttentionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAttentionModel) Insert(ctx context.Context, data *UserAttention) (sql.Result, error) {
	userAttentionIdKey := fmt.Sprintf("%s%v", cacheUserAttentionIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userAttentionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.AttentionId, data.IsDel)
	}, userAttentionIdKey)
	return ret, err
}

func (m *defaultUserAttentionModel) Update(ctx context.Context, data *UserAttention) error {
	userAttentionIdKey := fmt.Sprintf("%s%v", cacheUserAttentionIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAttentionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.AttentionId, data.IsDel, data.Id)
	}, userAttentionIdKey)
	return err
}

func (m *defaultUserAttentionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserAttentionIdPrefix, primary)
}

func (m *defaultUserAttentionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAttentionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserAttentionModel) tableName() string {
	return m.table
}
