// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFollowerFieldNames          = builder.RawFieldNames(&UserFollower{})
	userFollowerRows                = strings.Join(userFollowerFieldNames, ",")
	userFollowerRowsExpectAutoSet   = strings.Join(stringx.Remove(userFollowerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userFollowerRowsWithPlaceHolder = strings.Join(stringx.Remove(userFollowerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserFollowerIdPrefix = "cache:userFollower:id:"
)

type (
	userFollowerModel interface {
		Insert(ctx context.Context, data *UserFollower) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserFollower, error)
		Update(ctx context.Context, data *UserFollower) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserFollowerModel struct {
		sqlc.CachedConn
		table string
	}

	UserFollower struct {
		Id         int64        `db:"id"`          // 主键id
		UserId     int64        `db:"user_id"`     // 博主id
		FollowerId int64        `db:"follower_id"` // 粉丝id
		CreateTime sql.NullTime `db:"create_time"` // 创建时间，按时间排序
		IsDel      int64        `db:"is_del"`      // 是否删除 0 正常 1删除
	}
)

func newUserFollowerModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserFollowerModel {
	return &defaultUserFollowerModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_follower`",
	}
}

func (m *defaultUserFollowerModel) Delete(ctx context.Context, id int64) error {
	userFollowerIdKey := fmt.Sprintf("%s%v", cacheUserFollowerIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userFollowerIdKey)
	return err
}

func (m *defaultUserFollowerModel) FindOne(ctx context.Context, id int64) (*UserFollower, error) {
	userFollowerIdKey := fmt.Sprintf("%s%v", cacheUserFollowerIdPrefix, id)
	var resp UserFollower
	err := m.QueryRowCtx(ctx, &resp, userFollowerIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFollowerRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFollowerModel) Insert(ctx context.Context, data *UserFollower) (sql.Result, error) {
	userFollowerIdKey := fmt.Sprintf("%s%v", cacheUserFollowerIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userFollowerRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowerId, data.IsDel)
	}, userFollowerIdKey)
	return ret, err
}

func (m *defaultUserFollowerModel) Update(ctx context.Context, data *UserFollower) error {
	userFollowerIdKey := fmt.Sprintf("%s%v", cacheUserFollowerIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userFollowerRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.FollowerId, data.IsDel, data.Id)
	}, userFollowerIdKey)
	return err
}

func (m *defaultUserFollowerModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserFollowerIdPrefix, primary)
}

func (m *defaultUserFollowerModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userFollowerRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserFollowerModel) tableName() string {
	return m.table
}
