// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.0

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userRelationFieldNames          = builder.RawFieldNames(&UserRelation{})
	userRelationRows                = strings.Join(userRelationFieldNames, ",")
	userRelationRowsExpectAutoSet   = strings.Join(stringx.Remove(userRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRelationRowsWithPlaceHolder = strings.Join(stringx.Remove(userRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserRelationIdPrefix     = "cache:userRelation:id:"
	cacheUserRelationUserIdPrefix = "cache:userRelation:userId:"
)

type (
	userRelationModel interface {
		Insert(ctx context.Context, data *UserRelation) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserRelation, error)
		FindOneByUserId(ctx context.Context, userId int64) (*UserRelation, error)
		Update(ctx context.Context, data *UserRelation) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserRelationModel struct {
		sqlc.CachedConn
		table string
	}

	UserRelation struct {
		Id             int64 `db:"id"`              // 主键id
		UserId         int64 `db:"user_id"`         // 用户id
		AttentionCount int64 `db:"attention_count"` // 关注数
		FollowerCount  int64 `db:"follower_count"`  // 粉丝数
	}
)

func newUserRelationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserRelationModel {
	return &defaultUserRelationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_relation`",
	}
}

func (m *defaultUserRelationModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userRelationIdKey := fmt.Sprintf("%s%v", cacheUserRelationIdPrefix, id)
	userRelationUserIdKey := fmt.Sprintf("%s%v", cacheUserRelationUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userRelationIdKey, userRelationUserIdKey)
	return err
}

func (m *defaultUserRelationModel) FindOne(ctx context.Context, id int64) (*UserRelation, error) {
	userRelationIdKey := fmt.Sprintf("%s%v", cacheUserRelationIdPrefix, id)
	var resp UserRelation
	err := m.QueryRowCtx(ctx, &resp, userRelationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRelationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRelationModel) FindOneByUserId(ctx context.Context, userId int64) (*UserRelation, error) {
	userRelationUserIdKey := fmt.Sprintf("%s%v", cacheUserRelationUserIdPrefix, userId)
	var resp UserRelation
	err := m.QueryRowIndexCtx(ctx, &resp, userRelationUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userRelationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRelationModel) Insert(ctx context.Context, data *UserRelation) (sql.Result, error) {
	userRelationIdKey := fmt.Sprintf("%s%v", cacheUserRelationIdPrefix, data.Id)
	userRelationUserIdKey := fmt.Sprintf("%s%v", cacheUserRelationUserIdPrefix, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userRelationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.AttentionCount, data.FollowerCount)
	}, userRelationIdKey, userRelationUserIdKey)
	return ret, err
}

func (m *defaultUserRelationModel) Update(ctx context.Context, newData *UserRelation) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userRelationIdKey := fmt.Sprintf("%s%v", cacheUserRelationIdPrefix, data.Id)
	userRelationUserIdKey := fmt.Sprintf("%s%v", cacheUserRelationUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRelationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.AttentionCount, newData.FollowerCount, newData.Id)
	}, userRelationIdKey, userRelationUserIdKey)
	return err
}

func (m *defaultUserRelationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserRelationIdPrefix, primary)
}

func (m *defaultUserRelationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRelationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserRelationModel) tableName() string {
	return m.table
}
