// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: social.proto

package socialclient

import (
	"context"

	"github.com/hd2yao/ecshop/social/rpc/types/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FansListReq   = social.FansListReq
	FollowListReq = social.FollowListReq
	FollowReq     = social.FollowReq
	FollowResp    = social.FollowResp
	ListResp      = social.ListResp
	UserBrief     = social.UserBrief

	Social interface {
		// 博主关注
		BloggerFollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		// 博主取消关注
		BloggerUnfollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		// 粉丝关注（回关粉丝）
		FollowerFollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		// 粉丝取关（取消对粉丝的关注）
		FollowerUnfollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
		// 粉丝列表（参数仅 user_id，0 或不填表示当前用户）
		FansList(ctx context.Context, in *FansListReq, opts ...grpc.CallOption) (*ListResp, error)
		// 关注列表（无需 user_id，使用鉴权用户）
		FollowList(ctx context.Context, in *FollowListReq, opts ...grpc.CallOption) (*ListResp, error)
	}

	defaultSocial struct {
		cli zrpc.Client
	}
)

func NewSocial(cli zrpc.Client) Social {
	return &defaultSocial{
		cli: cli,
	}
}

// 博主关注
func (m *defaultSocial) BloggerFollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.BloggerFollow(ctx, in, opts...)
}

// 博主取消关注
func (m *defaultSocial) BloggerUnfollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.BloggerUnfollow(ctx, in, opts...)
}

// 粉丝关注（回关粉丝）
func (m *defaultSocial) FollowerFollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FollowerFollow(ctx, in, opts...)
}

// 粉丝取关（取消对粉丝的关注）
func (m *defaultSocial) FollowerUnfollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FollowerUnfollow(ctx, in, opts...)
}

// 粉丝列表（参数仅 user_id，0 或不填表示当前用户）
func (m *defaultSocial) FansList(ctx context.Context, in *FansListReq, opts ...grpc.CallOption) (*ListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FansList(ctx, in, opts...)
}

// 关注列表（无需 user_id，使用鉴权用户）
func (m *defaultSocial) FollowList(ctx context.Context, in *FollowListReq, opts ...grpc.CallOption) (*ListResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.FollowList(ctx, in, opts...)
}
