// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: social.proto

package server

import (
	"context"

	"github.com/hd2yao/ecshop/social/rpc/internal/logic"
	"github.com/hd2yao/ecshop/social/rpc/internal/svc"
	"github.com/hd2yao/ecshop/social/rpc/types/social"
)

type SocialServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedSocialServer
}

func NewSocialServer(svcCtx *svc.ServiceContext) *SocialServer {
	return &SocialServer{
		svcCtx: svcCtx,
	}
}

// 博主关注
func (s *SocialServer) BloggerFollow(ctx context.Context, in *social.FollowReq) (*social.FollowResp, error) {
	l := logic.NewBloggerFollowLogic(ctx, s.svcCtx)
	return l.BloggerFollow(in)
}

// 博主取消关注
func (s *SocialServer) BloggerUnfollow(ctx context.Context, in *social.FollowReq) (*social.FollowResp, error) {
	l := logic.NewBloggerUnfollowLogic(ctx, s.svcCtx)
	return l.BloggerUnfollow(in)
}

// 粉丝关注（回关粉丝）
func (s *SocialServer) FollowerFollow(ctx context.Context, in *social.FollowReq) (*social.FollowResp, error) {
	l := logic.NewFollowerFollowLogic(ctx, s.svcCtx)
	return l.FollowerFollow(in)
}

// 粉丝取关（取消对粉丝的关注）
func (s *SocialServer) FollowerUnfollow(ctx context.Context, in *social.FollowReq) (*social.FollowResp, error) {
	l := logic.NewFollowerUnfollowLogic(ctx, s.svcCtx)
	return l.FollowerUnfollow(in)
}

// 粉丝列表（参数仅 user_id，0 或不填表示当前用户）
func (s *SocialServer) FansList(ctx context.Context, in *social.FansListReq) (*social.ListResp, error) {
	l := logic.NewFansListLogic(ctx, s.svcCtx)
	return l.FansList(in)
}

// 关注列表（无需 user_id，使用鉴权用户）
func (s *SocialServer) FollowList(ctx context.Context, in *social.FollowListReq) (*social.ListResp, error) {
	l := logic.NewFollowListLogic(ctx, s.svcCtx)
	return l.FollowList(in)
}
