// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	food "github.com/hd2yao/ecshop/food/api/internal/handler/food"
	"github.com/hd2yao/ecshop/food/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuth},
			[]rest.Route{
				{
					// 查询单个美食基础信息
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: food.GetFoodHandler(serverCtx),
				},
				{
					// 新增/修改美食信息（food_id为0或未提供时为新增，否则为修改）
					Method:  http.MethodPost,
					Path:    "/create-or-update",
					Handler: food.CreateOrUpdateFoodHandler(serverCtx),
				},
				{
					// 查询我的美食列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: food.GetMyFoodListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/food"),
	)
}
