// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: rpc/social.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 关注/取关请求
// 注意：
// - operator_id 由 API 层根据 token 解析后传入，表示操作者ID
// - user_id 为目标用户ID（被关注/取关的用户）
type FollowReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    int64                  `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者ID（当前登录用户）
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 目标用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowReq) Reset() {
	*x = FollowReq{}
	mi := &file_rpc_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowReq) ProtoMessage() {}

func (x *FollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowReq.ProtoReflect.Descriptor instead.
func (*FollowReq) Descriptor() ([]byte, []int) {
	return file_rpc_social_proto_rawDescGZIP(), []int{0}
}

func (x *FollowReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *FollowReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 通用响应
type FollowResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResp) Reset() {
	*x = FollowResp{}
	mi := &file_rpc_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResp) ProtoMessage() {}

func (x *FollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResp.ProtoReflect.Descriptor instead.
func (*FollowResp) Descriptor() ([]byte, []int) {
	return file_rpc_social_proto_rawDescGZIP(), []int{1}
}

func (x *FollowResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FollowResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 粉丝列表请求
// - operator_id 为操作者ID（当前登录用户，用于计算 is_follow / is_mutual）
// - user_id 为要查看粉丝列表的用户ID；为 0 时表示当前登录用户
type FansListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    int64                  `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者ID（当前登录用户）
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 目标用户ID；0 表示当前用户
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FansListReq) Reset() {
	*x = FansListReq{}
	mi := &file_rpc_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FansListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FansListReq) ProtoMessage() {}

func (x *FansListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FansListReq.ProtoReflect.Descriptor instead.
func (*FansListReq) Descriptor() ([]byte, []int) {
	return file_rpc_social_proto_rawDescGZIP(), []int{2}
}

func (x *FansListReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *FansListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FansListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FansListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 关注列表请求（仅分页）
// - operator_id 为操作者ID（当前登录用户）
type FollowListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    int64                  `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者ID（当前登录用户）
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListReq) Reset() {
	*x = FollowListReq{}
	mi := &file_rpc_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListReq) ProtoMessage() {}

func (x *FollowListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListReq.ProtoReflect.Descriptor instead.
func (*FollowListReq) Descriptor() ([]byte, []int) {
	return file_rpc_social_proto_rawDescGZIP(), []int{3}
}

func (x *FollowListReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *FollowListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FollowListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 简要用户信息
type UserBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	IsFollow      bool                   `protobuf:"varint,4,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"` // 当前登录用户是否已关注
	IsMutual      bool                   `protobuf:"varint,5,opt,name=is_mutual,json=isMutual,proto3" json:"is_mutual,omitempty"` // 是否互相关注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBrief) Reset() {
	*x = UserBrief{}
	mi := &file_rpc_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBrief) ProtoMessage() {}

func (x *UserBrief) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBrief.ProtoReflect.Descriptor instead.
func (*UserBrief) Descriptor() ([]byte, []int) {
	return file_rpc_social_proto_rawDescGZIP(), []int{4}
}

func (x *UserBrief) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserBrief) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserBrief) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

func (x *UserBrief) GetIsMutual() bool {
	if x != nil {
		return x.IsMutual
	}
	return false
}

// 列表响应
type ListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	List          []*UserBrief           `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResp) Reset() {
	*x = ListResp{}
	mi := &file_rpc_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResp) ProtoMessage() {}

func (x *ListResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResp.ProtoReflect.Descriptor instead.
func (*ListResp) Descriptor() ([]byte, []int) {
	return file_rpc_social_proto_rawDescGZIP(), []int{5}
}

func (x *ListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListResp) GetList() []*UserBrief {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_rpc_social_proto protoreflect.FileDescriptor

const file_rpc_social_proto_rawDesc = "" +
	"\n" +
	"\x10rpc/social.proto\x12\x06social\"E\n" +
	"\tFollowReq\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\":\n" +
	"\n" +
	"FollowResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"o\n" +
	"\vFansListReq\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"X\n" +
	"\rFollowListReq\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x03R\n" +
	"operatorId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\x8a\x01\n" +
	"\tUserBrief\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1b\n" +
	"\tis_follow\x18\x04 \x01(\bR\bisFollow\x12\x1b\n" +
	"\tis_mutual\x18\x05 \x01(\bR\bisMutual\"\x9d\x01\n" +
	"\bListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x04list\x18\x03 \x03(\v2\x11.social.UserBriefR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size2\xd8\x02\n" +
	"\x06Social\x126\n" +
	"\rBloggerFollow\x12\x11.social.FollowReq\x1a\x12.social.FollowResp\x128\n" +
	"\x0fBloggerUnfollow\x12\x11.social.FollowReq\x1a\x12.social.FollowResp\x127\n" +
	"\x0eFollowerFollow\x12\x11.social.FollowReq\x1a\x12.social.FollowResp\x129\n" +
	"\x10FollowerUnfollow\x12\x11.social.FollowReq\x1a\x12.social.FollowResp\x121\n" +
	"\bFansList\x12\x13.social.FansListReq\x1a\x10.social.ListResp\x125\n" +
	"\n" +
	"FollowList\x12\x15.social.FollowListReq\x1a\x10.social.ListRespB\n" +
	"Z\b./socialb\x06proto3"

var (
	file_rpc_social_proto_rawDescOnce sync.Once
	file_rpc_social_proto_rawDescData []byte
)

func file_rpc_social_proto_rawDescGZIP() []byte {
	file_rpc_social_proto_rawDescOnce.Do(func() {
		file_rpc_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_social_proto_rawDesc), len(file_rpc_social_proto_rawDesc)))
	})
	return file_rpc_social_proto_rawDescData
}

var file_rpc_social_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpc_social_proto_goTypes = []any{
	(*FollowReq)(nil),     // 0: social.FollowReq
	(*FollowResp)(nil),    // 1: social.FollowResp
	(*FansListReq)(nil),   // 2: social.FansListReq
	(*FollowListReq)(nil), // 3: social.FollowListReq
	(*UserBrief)(nil),     // 4: social.UserBrief
	(*ListResp)(nil),      // 5: social.ListResp
}
var file_rpc_social_proto_depIdxs = []int32{
	4, // 0: social.ListResp.list:type_name -> social.UserBrief
	0, // 1: social.Social.BloggerFollow:input_type -> social.FollowReq
	0, // 2: social.Social.BloggerUnfollow:input_type -> social.FollowReq
	0, // 3: social.Social.FollowerFollow:input_type -> social.FollowReq
	0, // 4: social.Social.FollowerUnfollow:input_type -> social.FollowReq
	2, // 5: social.Social.FansList:input_type -> social.FansListReq
	3, // 6: social.Social.FollowList:input_type -> social.FollowListReq
	1, // 7: social.Social.BloggerFollow:output_type -> social.FollowResp
	1, // 8: social.Social.BloggerUnfollow:output_type -> social.FollowResp
	1, // 9: social.Social.FollowerFollow:output_type -> social.FollowResp
	1, // 10: social.Social.FollowerUnfollow:output_type -> social.FollowResp
	5, // 11: social.Social.FansList:output_type -> social.ListResp
	5, // 12: social.Social.FollowList:output_type -> social.ListResp
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_social_proto_init() }
func file_rpc_social_proto_init() {
	if File_rpc_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_social_proto_rawDesc), len(file_rpc_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_social_proto_goTypes,
		DependencyIndexes: file_rpc_social_proto_depIdxs,
		MessageInfos:      file_rpc_social_proto_msgTypes,
	}.Build()
	File_rpc_social_proto = out.File
	file_rpc_social_proto_goTypes = nil
	file_rpc_social_proto_depIdxs = nil
}
