// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: rpc/social.proto

package social

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Social_BloggerFollow_FullMethodName    = "/social.Social/BloggerFollow"
	Social_BloggerUnfollow_FullMethodName  = "/social.Social/BloggerUnfollow"
	Social_FollowerFollow_FullMethodName   = "/social.Social/FollowerFollow"
	Social_FollowerUnfollow_FullMethodName = "/social.Social/FollowerUnfollow"
	Social_FansList_FullMethodName         = "/social.Social/FansList"
	Social_FollowList_FullMethodName       = "/social.Social/FollowList"
)

// SocialClient is the client API for Social service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 关注/取关/列表服务
type SocialClient interface {
	// 博主关注
	BloggerFollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
	// 博主取消关注
	BloggerUnfollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
	// 粉丝关注（回关粉丝）
	FollowerFollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
	// 粉丝取关（取消对粉丝的关注）
	FollowerUnfollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error)
	// 粉丝列表（参数仅 user_id，0 或不填表示当前用户）
	FansList(ctx context.Context, in *FansListReq, opts ...grpc.CallOption) (*ListResp, error)
	// 关注列表（无需 user_id，使用鉴权用户）
	FollowList(ctx context.Context, in *FollowListReq, opts ...grpc.CallOption) (*ListResp, error)
}

type socialClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialClient(cc grpc.ClientConnInterface) SocialClient {
	return &socialClient{cc}
}

func (c *socialClient) BloggerFollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResp)
	err := c.cc.Invoke(ctx, Social_BloggerFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) BloggerUnfollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResp)
	err := c.cc.Invoke(ctx, Social_BloggerUnfollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FollowerFollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResp)
	err := c.cc.Invoke(ctx, Social_FollowerFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FollowerUnfollow(ctx context.Context, in *FollowReq, opts ...grpc.CallOption) (*FollowResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResp)
	err := c.cc.Invoke(ctx, Social_FollowerUnfollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FansList(ctx context.Context, in *FansListReq, opts ...grpc.CallOption) (*ListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResp)
	err := c.cc.Invoke(ctx, Social_FansList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) FollowList(ctx context.Context, in *FollowListReq, opts ...grpc.CallOption) (*ListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResp)
	err := c.cc.Invoke(ctx, Social_FollowList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServer is the server API for Social service.
// All implementations must embed UnimplementedSocialServer
// for forward compatibility.
//
// 关注/取关/列表服务
type SocialServer interface {
	// 博主关注
	BloggerFollow(context.Context, *FollowReq) (*FollowResp, error)
	// 博主取消关注
	BloggerUnfollow(context.Context, *FollowReq) (*FollowResp, error)
	// 粉丝关注（回关粉丝）
	FollowerFollow(context.Context, *FollowReq) (*FollowResp, error)
	// 粉丝取关（取消对粉丝的关注）
	FollowerUnfollow(context.Context, *FollowReq) (*FollowResp, error)
	// 粉丝列表（参数仅 user_id，0 或不填表示当前用户）
	FansList(context.Context, *FansListReq) (*ListResp, error)
	// 关注列表（无需 user_id，使用鉴权用户）
	FollowList(context.Context, *FollowListReq) (*ListResp, error)
	mustEmbedUnimplementedSocialServer()
}

// UnimplementedSocialServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServer struct{}

func (UnimplementedSocialServer) BloggerFollow(context.Context, *FollowReq) (*FollowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BloggerFollow not implemented")
}
func (UnimplementedSocialServer) BloggerUnfollow(context.Context, *FollowReq) (*FollowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BloggerUnfollow not implemented")
}
func (UnimplementedSocialServer) FollowerFollow(context.Context, *FollowReq) (*FollowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowerFollow not implemented")
}
func (UnimplementedSocialServer) FollowerUnfollow(context.Context, *FollowReq) (*FollowResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowerUnfollow not implemented")
}
func (UnimplementedSocialServer) FansList(context.Context, *FansListReq) (*ListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FansList not implemented")
}
func (UnimplementedSocialServer) FollowList(context.Context, *FollowListReq) (*ListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowList not implemented")
}
func (UnimplementedSocialServer) mustEmbedUnimplementedSocialServer() {}
func (UnimplementedSocialServer) testEmbeddedByValue()                {}

// UnsafeSocialServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServer will
// result in compilation errors.
type UnsafeSocialServer interface {
	mustEmbedUnimplementedSocialServer()
}

func RegisterSocialServer(s grpc.ServiceRegistrar, srv SocialServer) {
	// If the following call panics, it indicates UnimplementedSocialServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Social_ServiceDesc, srv)
}

func _Social_BloggerFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).BloggerFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_BloggerFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).BloggerFollow(ctx, req.(*FollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_BloggerUnfollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).BloggerUnfollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_BloggerUnfollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).BloggerUnfollow(ctx, req.(*FollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FollowerFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FollowerFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FollowerFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FollowerFollow(ctx, req.(*FollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FollowerUnfollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FollowerUnfollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FollowerUnfollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FollowerUnfollow(ctx, req.(*FollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FansList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FansListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FansList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FansList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FansList(ctx, req.(*FansListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_FollowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).FollowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_FollowList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).FollowList(ctx, req.(*FollowListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Social_ServiceDesc is the grpc.ServiceDesc for Social service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Social_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.Social",
	HandlerType: (*SocialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BloggerFollow",
			Handler:    _Social_BloggerFollow_Handler,
		},
		{
			MethodName: "BloggerUnfollow",
			Handler:    _Social_BloggerUnfollow_Handler,
		},
		{
			MethodName: "FollowerFollow",
			Handler:    _Social_FollowerFollow_Handler,
		},
		{
			MethodName: "FollowerUnfollow",
			Handler:    _Social_FollowerUnfollow_Handler,
		},
		{
			MethodName: "FansList",
			Handler:    _Social_FansList_Handler,
		},
		{
			MethodName: "FollowList",
			Handler:    _Social_FollowList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/social.proto",
}
