// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	follow "github.com/hd2yao/ecshop/social/api/internal/handler/follow"
	"github.com/hd2yao/ecshop/social/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JWTAuth},
			[]rest.Route{
				{
					// 粉丝列表（传 user_id，默认当前用户）
					Method:  http.MethodGet,
					Path:    "/fans/list",
					Handler: follow.FansListHandler(serverCtx),
				},
				{
					// 博主关注
					Method:  http.MethodPost,
					Path:    "/follow",
					Handler: follow.BloggerFollowHandler(serverCtx),
				},
				{
					// 关注列表（无需参数，使用 token 中用户）
					Method:  http.MethodGet,
					Path:    "/follow/list",
					Handler: follow.FollowListHandler(serverCtx),
				},
				{
					// 粉丝关注（回关粉丝）
					Method:  http.MethodPost,
					Path:    "/follower/follow",
					Handler: follow.FollowerFollowHandler(serverCtx),
				},
				{
					// 粉丝取关（取消对粉丝的关注）
					Method:  http.MethodPost,
					Path:    "/follower/unfollow",
					Handler: follow.FollowerUnfollowHandler(serverCtx),
				},
				{
					// 博主取消关注
					Method:  http.MethodPost,
					Path:    "/unfollow",
					Handler: follow.BloggerUnfollowHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/social"),
	)
}
