// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: food.proto

package foodclient

import (
	"context"

	"github.com/hd2yao/ecshop/food/rpc/types/food"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrUpdateFoodReq  = food.CreateOrUpdateFoodReq
	CreateOrUpdateFoodResp = food.CreateOrUpdateFoodResp
	FoodInfo               = food.FoodInfo
	FoodListItem           = food.FoodListItem
	FoodStepDetail         = food.FoodStepDetail
	GetFoodReq             = food.GetFoodReq
	GetFoodResp            = food.GetFoodResp
	GetMyFoodListReq       = food.GetMyFoodListReq
	GetMyFoodListResp      = food.GetMyFoodListResp

	Food interface {
		// 查询单个美食基础信息
		GetFood(ctx context.Context, in *GetFoodReq, opts ...grpc.CallOption) (*GetFoodResp, error)
		// 查询我的美食列表
		GetMyFoodList(ctx context.Context, in *GetMyFoodListReq, opts ...grpc.CallOption) (*GetMyFoodListResp, error)
		// 新增/修改美食信息
		CreateOrUpdateFood(ctx context.Context, in *CreateOrUpdateFoodReq, opts ...grpc.CallOption) (*CreateOrUpdateFoodResp, error)
	}

	defaultFood struct {
		cli zrpc.Client
	}
)

func NewFood(cli zrpc.Client) Food {
	return &defaultFood{
		cli: cli,
	}
}

// 查询单个美食基础信息
func (m *defaultFood) GetFood(ctx context.Context, in *GetFoodReq, opts ...grpc.CallOption) (*GetFoodResp, error) {
	client := food.NewFoodClient(m.cli.Conn())
	return client.GetFood(ctx, in, opts...)
}

// 查询我的美食列表
func (m *defaultFood) GetMyFoodList(ctx context.Context, in *GetMyFoodListReq, opts ...grpc.CallOption) (*GetMyFoodListResp, error) {
	client := food.NewFoodClient(m.cli.Conn())
	return client.GetMyFoodList(ctx, in, opts...)
}

// 新增/修改美食信息
func (m *defaultFood) CreateOrUpdateFood(ctx context.Context, in *CreateOrUpdateFoodReq, opts ...grpc.CallOption) (*CreateOrUpdateFoodResp, error) {
	client := food.NewFoodClient(m.cli.Conn())
	return client.CreateOrUpdateFood(ctx, in, opts...)
}
